// File: app/frontend/src/data/navGraph.generated.ts
// 🚀 AUTO-GENERATED by scripts/generate-nav-data.ts — DO NOT EDIT BY HAND.
// Regenerated automatically on every "dev" and "build" run from graph.ts + blogPosts.ts.
// This is a deliberately slim subset (nav-relevant fields only) so that
// Header/Footer/NavigationCompiler — which render on every route — don't
// pull the full knowledge graph or full rich-content payload into the main entry bundle.

export const NAV_GRAPH = {
  "business": {
    "id": "biz-kcroc",
    "entityType": "Business",
    "isActive": true,
    "title": "Kuwait Computer Repair On Call",
    "legalName": "Kuwait Computer Repair On Call",
    "alternateName": "KCROC",
    "telephone": "96555301913",
    "streetAddress": "Ibn Khaldoun St, Al Mullah Complex, Basement Shop 19",
    "addressLocality": "Hawalli",
    "addressRegion": "Hawalli Governorate",
    "addressCountry": "KW",
    "coords": {
      "lat": 29.3416921515256,
      "lng": 48.00761257498341
    },
    "websiteUrl": "https://www.computerrepairkuwait.com",
    "logoUrl": "https://www.computerrepairkuwait.com/logo.webp",
    "email": "info@computerrepairkuwait.com",
    "priceRange": "$$",
    "openingHours": "Open daily 10:00 AM – 10:00 PM",
    "schemaOpeningHours": {
      "dayOfWeek": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday"
      ],
      "opens": "10:00",
      "closes": "22:00"
    },
    "aggregateRating": {
      "ratingValue": "4.9",
      "reviewCount": 158,
      "bestRating": 5
    },
    "socialLinks": {
      "facebook": "https://www.facebook.com/computerrepairkuwait",
      "instagram": "https://www.instagram.com/computerrepairkuwait",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJzapykEqbzz8RZsrwoaORhjY"
    },
    "aiSummary": "Kuwait Computer Repair On Call (KCROC) is a Hawalli-based component-level computer repair specialist. Services include laptop and MacBook repair, gaming PC repair, motherboard chip-level diagnostics, screen replacement, battery replacement, charging-port repair, hinge and chassis repair, keyboard replacement, SSD and RAM upgrades, liquid-damage repair, gaming laptop thermal servicing, and virus removal. Free pickup and delivery across all Kuwait governorates. 30-day warranty on completed repairs. No Fix, No Fee policy."
  },
  "footer": {
    "services": [
      {
        "label": "Laptop Repair Kuwait",
        "path": "/laptop-repair-kuwait"
      },
      {
        "label": "MacBook Repair Kuwait",
        "path": "/macbook-repair-kuwait"
      },
      {
        "label": "Gaming PC Repair Kuwait",
        "path": "/gaming-pc-repair-kuwait"
      },
      {
        "label": "Gaming Laptop Cleaning Kuwait",
        "path": "/gaming-laptop-cleaning-kuwait"
      },
      {
        "label": "Motherboard Repair Kuwait",
        "path": "/motherboard-repair-kuwait"
      },
      {
        "label": "Screen Replacement Kuwait",
        "path": "/laptop-screen-repair-kuwait"
      },
      {
        "label": "Battery Replacement Kuwait",
        "path": "/battery-replacement-kuwait"
      },
      {
        "label": "Laptop Charging Port Repair",
        "path": "/laptop-charging-port-repair-kuwait"
      },
      {
        "label": "Laptop Hinge & Chassis Repair",
        "path": "/laptop-hinge-repair-kuwait"
      },
      {
        "label": "Laptop Keyboard Replacement",
        "path": "/laptop-keyboard-replacement-kuwait"
      },
      {
        "label": "SSD & RAM Upgrade Kuwait",
        "path": "/ssd-ram-upgrade-kuwait"
      },
      {
        "label": "Laptop Liquid Damage Repair",
        "path": "/laptop-liquid-damage-repair-kuwait"
      }
    ],
    "company": [
      {
        "label": "About us",
        "path": "/about"
      },
      {
        "label": "Contact",
        "path": "/contact"
      },
      {
        "label": "Tech News",
        "path": "/news"
      },
      {
        "label": "Tech Blog",
        "path": "/blog"
      },
      {
        "label": "Battery Health Guide",
        "path": "/guides/laptop-battery-warning-signs"
      },
      {
        "label": "FAQ",
        "path": "/faq"
      },
      {
        "label": "Pricing",
        "path": "/pricing"
      },
      {
        "label": "Computer Repair Near Me",
        "path": "/near-me"
      },
      {
        "label": "All Service Areas",
        "path": "/locations"
      }
    ],
    "areas": [
      {
        "label": "Computer Repair Hawalli",
        "path": "/location/hawalli"
      },
      {
        "label": "Computer Repair Salmiya",
        "path": "/location/salmiya"
      },
      {
        "label": "Computer Repair Kuwait City",
        "path": "/location/kuwait-city"
      },
      {
        "label": "Computer Repair Farwaniya",
        "path": "/location/farwaniya"
      },
      {
        "label": "Computer Repair Jahra",
        "path": "/location/jahra"
      },
      {
        "label": "Computer Repair Ahmadi",
        "path": "/location/ahmadi"
      },
      {
        "label": "Computer Repair Fahaheel",
        "path": "/location/fahaheel"
      },
      {
        "label": "Computer Repair Mangaf",
        "path": "/location/mangaf"
      },
      {
        "label": "Computer Repair Abu Halifa",
        "path": "/location/abu-halifa"
      },
      {
        "label": "Computer Repair Jabriya",
        "path": "/location/jabriya"
      },
      {
        "label": "Computer Repair Mubarak Al-Kabeer",
        "path": "/location/mubarak-al-kabeer"
      },
      {
        "label": "Computer Repair Fintas",
        "path": "/location/fintas"
      },
      {
        "label": "Computer Repair Sabah Al-Salem",
        "path": "/location/sabah-al-salem"
      },
      {
        "label": "Computer Repair Salwa",
        "path": "/location/salwa"
      },
      {
        "label": "Computer Repair Rumaithiya",
        "path": "/location/rumaithiya"
      },
      {
        "label": "Computer Repair Shaab",
        "path": "/location/shaab"
      },
      {
        "label": "Computer Repair Surra",
        "path": "/location/surra"
      },
      {
        "label": "Computer Repair Khaitan",
        "path": "/location/khaitan"
      },
      {
        "label": "Computer Repair Riggae",
        "path": "/location/riggae"
      },
      {
        "label": "Computer Repair Ardiya",
        "path": "/location/ardiya"
      },
      {
        "label": "Computer Repair Mahboula",
        "path": "/location/mahboula"
      },
      {
        "label": "Computer Repair Qurain",
        "path": "/location/qurain"
      },
      {
        "label": "Computer Repair Qortuba",
        "path": "/location/qortuba"
      },
      {
        "label": "Computer Repair Rawda",
        "path": "/location/rawda"
      },
      {
        "label": "Computer Repair Messila",
        "path": "/location/messila"
      },
      {
        "label": "Computer Repair Adailiya",
        "path": "/location/adailiya"
      }
    ]
  },
  "trustBadges": [
    {
      "id": "badge-privacy",
      "title": "Privacy Protected",
      "iconKey": "ShieldCheck"
    },
    {
      "id": "badge-pickup",
      "title": "Free Pickup & Delivery",
      "iconKey": "Truck"
    },
    {
      "id": "badge-warranty",
      "title": "30-Day Repair Warranty",
      "iconKey": "Clock"
    },
    {
      "id": "badge-esd",
      "title": "ESD-Safe Lab",
      "iconKey": "Zap"
    }
  ],
  "services": [
    {
      "id": "srv-charging-port",
      "slug": "laptop-charging-port-repair-kuwait",
      "title": "Laptop Charging Port Repair Kuwait",
      "description": "If your laptop only charges when the cable is held at an angle, the charging port feels loose, USB-C charging suddenly stopped, or the machine shows no response from a known-good adapter, the fault may be the connector or the power path behind it. KCROC tests the adapter, port, connector pins, charging circuit, and motherboard before replacing anything. When the board is repairable, we micro-solder the damaged connector or failed power component instead of defaulting to a full motherboard replacement.",
      "iconKey": "cpu",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-hinge",
      "slug": "laptop-hinge-repair-kuwait",
      "title": "Laptop Hinge & Chassis Repair Kuwait",
      "description": "A hinge that is stiff, cracking the bezel, or pulling the screen assembly away from the chassis should not be ignored. Continued force can damage the display cable, crack the panel, or tear the hinge mounts out of the plastic chassis. KCROC checks hinge tension, mounting points, bezel condition, lid alignment, and cable routing, then repairs the structural damage or replaces the failed hinge assembly where required.",
      "iconKey": "laptop",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-keyboard",
      "slug": "laptop-keyboard-replacement-kuwait",
      "title": "Laptop Keyboard Replacement Kuwait",
      "description": "Dead keys, repeated characters, liquid-damaged keyboards, stuck keys, and keyboards that stop responding can come from the keyboard assembly, ribbon connection, liquid contamination, or the motherboard input circuit. KCROC tests the failure first, then replaces the keyboard or repairs the related connection where appropriate. For MacBooks, we also distinguish between butterfly and Magic Keyboard generations before ordering parts.",
      "iconKey": "laptop",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-macbook-screen",
      "slug": "macbook-screen-replacement-kuwait",
      "title": "MacBook Screen Replacement Kuwait",
      "description": "MacBook display damage needs more than a generic laptop panel swap. KCROC identifies the exact MacBook generation, screen assembly and display fault first, then matches the replacement to the model before installation. For cracked, black or flickering displays, we also check the display cable, backlight path and surrounding hardware so a full screen assembly is not ordered when a smaller fault explains the symptom.",
      "iconKey": "monitor",
      "popular": true,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-gaming-laptop",
      "slug": "gaming-laptop-repair-kuwait",
      "title": "Gaming Laptop Repair Kuwait",
      "description": "Gaming laptops combine high-wattage CPU and GPU hardware with compact cooling, so the same symptom can come from heat, power, display, memory, firmware or board-level faults. KCROC diagnoses the actual cause before recommending a part swap. We work on ASUS ROG and TUF, Lenovo Legion, MSI, Acer Predator, HP OMEN and other performance laptops, with Kuwait-wide pickup and delivery from our Hawalli laboratory.",
      "iconKey": "gaming",
      "popular": true,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": false
    },
    {
      "id": "srv-ssd-ram",
      "slug": "ssd-ram-upgrade-kuwait",
      "title": "SSD & RAM Upgrade Kuwait",
      "description": "If a laptop takes minutes to boot, browsers stutter under normal workloads, or Windows constantly runs short of usable memory, an SSD or RAM upgrade can produce a much larger real-world improvement than random software tweaks. KCROC checks the existing storage interface, memory type and upgrade limits first. Where practical, we can clone the existing system to the new SSD, verify the boot environment, and test the upgraded machine under normal workloads.",
      "iconKey": "cpu",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-liquid-damage",
      "slug": "laptop-liquid-damage-repair-kuwait",
      "title": "Laptop Liquid Damage Repair Kuwait",
      "description": "Coffee, water, juice and other spills can create short circuits immediately and corrosion that continues after the visible liquid is gone. KCROC isolates power, documents the affected areas, inspects connectors and board traces, and cleans contamination before deciding which components can be saved. The objective is to repair the original electronics where practical, while being honest when corrosion or component damage makes a repair uneconomical.",
      "iconKey": "cpu",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-macbook",
      "slug": "macbook-repair-kuwait",
      "title": "MacBook Repair Kuwait",
      "description": "Your MacBook won't turn on, a spilled drink has just hit the keyboard, or neither Thunderbolt port will charge it anymore — and an Apple Authorized Service Provider has quoted a full motherboard replacement that costs hundreds of KWD and, on most Apple Silicon models, means starting over with zero access to your original files. That last part isn't a scare tactic — it's how the hardware works: on M1/M2/M3 MacBooks, storage is soldered directly to the board and encrypted against that specific board's Secure Enclave, so a swapped board is a genuinely different machine as far as your data is concerned. We take the other path. Using thermal imaging and a multimeter, we trace the fault to the exact failed component — a shorted MOSFET, a blown power IC, a corroded trace — and repair that one point via micro-soldering, on your original board. Your SSD, your Secure Enclave, and your data stay exactly where they were.",
      "iconKey": "apple",
      "popular": true,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-laptop",
      "slug": "laptop-repair-kuwait",
      "title": "Laptop Repair Kuwait",
      "description": "Everyday Windows laptops—from budget student IdeaPads to high-end XPS workstations—face a tough life. Between daily transport, dropped bags, and Kuwait's extreme summer heat combined with fine desert dust, mechanical and thermal failures are inevitable. We see it every day: hinges separating from plastic chassis, DC charging jacks pushed inward, cooling fans grinding or seizing, and systems slowing to a crawl. Instead of telling you to buy a new laptop, we fix the actual broken part. We repair snapped hinges with structural resin, micro-solder broken charging ports directly to the motherboard, ultrasonic-clean dust-choked cooling systems, and revive slow systems with SSD and RAM upgrades. We stock OEM and high-grade compatible parts for Dell, HP, Lenovo, ASUS, Acer, and MSI.",
      "iconKey": "laptop",
      "popular": true,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-desktop-pc",
      "slug": "desktop-pc-repair-kuwait",
      "title": "Desktop & PC Repair Kuwait",
      "description": "Desktop PC repair in Kuwait for home computers, office desktops, workstations, pre-built towers and custom PCs. KCROC diagnoses the actual hardware or software fault before recommending a replacement. We handle power failures, no display, Windows boot problems, blue screens, overheating, fan faults, storage and SSD issues, RAM instability, motherboard faults, PSU-related shutdowns and hardware upgrades. Where a component-level repair is technically practical, we repair the failed stage instead of defaulting to a full motherboard or system replacement. Free pickup and delivery are available across Kuwait, with repair completed at the Hawalli laboratory.",
      "iconKey": "monitor",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-gaming",
      "slug": "gaming-pc-repair-kuwait",
      "title": "Gaming PC Repair Kuwait",
      "description": "Need gaming computer repair in Kuwait? If your gaming PC shuts down mid-match, shows no display, stutters, drops FPS, overheats, crashes, artifacts, or refuses to power on, KCROC diagnoses the failure before recommending an expensive part swap. We use thermal imaging, controlled load testing and component-level diagnostics for custom desktops, pre-built gaming PCs, standalone GPUs, liquid-cooled systems and high-performance rigs. We service NVIDIA GeForce RTX and AMD Radeon systems, Ryzen and Intel builds, and major gaming-PC families. Where technically repairable, we repair the failed stage instead of defaulting to a full motherboard or GPU replacement. Free pickup and delivery are available across Kuwait, with a 30-day repair warranty.",
      "iconKey": "gaming",
      "popular": true,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-gaming-laptop-cleaning",
      "slug": "gaming-laptop-cleaning-kuwait",
      "title": "Gaming Laptop Cleaning & Thermal Repaste Kuwait",
      "description": "If your gaming laptop is running hotter than it used to, the fans never seem to spool down, or your frame rate falls off during long sessions, the cooling system usually needs professional attention rather than a factory reset. Our gaming laptop thermal service follows a complete workflow — inspect, diagnose, clean, service the thermal interfaces, reassemble and test under load — so thermal paste replacement is only one part of what happens, not the whole plan. Kuwait's higher ambient temperatures reduce the thermal headroom available to a laptop during sustained CPU/GPU workloads, and airborne dust can build up inside the cooling system faster than in cooler, drier climates, which is why regular thermal maintenance matters more here than the generic advice most laptops ship with. We work on ASUS ROG and TUF Gaming, Lenovo Legion, MSI, Acer Predator, Alienware, Razer Blade, HP OMEN and Victus, Dell G Series, Gigabyte AORUS and other comparable gaming laptops. Pricing is confirmed after we've seen the model and symptoms — send us a WhatsApp message for a free assessment, and pickup and delivery are free anywhere in Kuwait.",
      "iconKey": "gaming",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-motherboard",
      "slug": "motherboard-repair-kuwait",
      "title": "Motherboard Repair Kuwait",
      "description": "A laptop that's completely dead, one that shuts off randomly during normal use, or one a retail shop already quoted a \"full motherboard replacement\" for — these are the cases where component-level repair actually matters most, because a motherboard replacement usually costs more than the laptop is worth once you're past the second or third year of ownership. Most repair counters carry one tool for a dead board: swap the whole thing. We carry a multimeter, a thermal camera, and boardview schematics, and use them to trace the fault to the single component that actually failed — a shorted MOSFET, a blown fuse, a degraded capacitor, a corroded trace from an old spill — and repair that one point instead. The rest of the board, and anything soldered to it, stays exactly as it was.",
      "iconKey": "cpu",
      "popular": true,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-screen",
      "slug": "laptop-screen-repair-kuwait",
      "title": "Screen Replacement Kuwait",
      "description": "A cracked panel, a screen full of vertical lines, or a display that flickers whenever the lid moves doesn't mean the laptop is done — in almost every case it's a screen or cable fault, not a motherboard problem, and it's fixable the same day if the panel is in stock. We stock standard 14\" and 15.6\" FHD, IPS, and OLED panels for Dell, HP, Lenovo, ASUS, and Acer, plus Retina panels for MacBook Air and Pro. Kuwait's heat and dust also take a toll here specifically: display cables routed near the hinge flex thousands of times a year and wear through faster in high-temperature environments, which is why a \"cracked screen\" call often turns out to be a cable fault once we open the lid — a cheaper fix than a full panel.",
      "iconKey": "monitor",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": true,
      "hasPricing": true
    },
    {
      "id": "srv-battery",
      "slug": "battery-replacement-kuwait",
      "title": "Laptop & MacBook Battery Replacement Kuwait",
      "description": "A battery that drains in under an hour, a laptop that shuts down at \"30% remaining,\" a charge percentage that jumps from 60% to 20% with no warning, or a trackpad that's started lifting on one side — these are five different symptoms, and not all of them mean the battery itself is the problem. A battery that reports 0% and won't charge at all is sometimes a dead cell, and sometimes a failed charging IC on the motherboard that would leave a brand-new battery just as unresponsive. That's why we test the charging circuit and power delivery path before we quote a replacement — we replace batteries only after confirming the battery, not the charging system, is the actual cause. In Kuwait, batteries also fail faster than the manufacturer's spec sheet assumes: lithium-ion cells degrade measurably faster at sustained temperatures above 40°C, and a laptop left in a parked car or by a sunlit window for part of the day pushes internal temperatures well past that.",
      "iconKey": "battery",
      "popular": false,
      "noFixNoFee": true,
      "hasManyFeatures": true,
      "hasPricing": true
    }
  ],
  "brands": [
    {
      "id": "brand-dell",
      "slug": "dell-laptop-repair-kuwait",
      "title": "Dell Laptop Repair Kuwait",
      "description": "Dell laptops — Inspiron, Latitude, XPS, and Alienware — have specific failure patterns in Kuwait's climate. The cooling systems on Dell Inspiron and Latitude models are particularly vulnerable to dust ingress from Kuwait's particulate-heavy air. XPS models use soldered RAM and storage, making component-level repair the only cost-effective path when hardware fails.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": true
    },
    {
      "id": "brand-hp",
      "slug": "hp-laptop-repair-kuwait",
      "title": "HP Laptop Repair Kuwait",
      "description": "HP laptops — from the budget Pavilion to the business EliteBook — are among the most repaired devices in our Hawalli lab. HP's power management systems are particularly sensitive to Kuwait's frequent voltage fluctuations, which cause power IC failures more commonly than in other markets.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": true
    },
    {
      "id": "brand-lenovo",
      "slug": "lenovo-laptop-repair-kuwait",
      "title": "Lenovo Laptop Repair Kuwait",
      "description": "Independent Lenovo laptop repair in Kuwait for ThinkPad, IdeaPad, Yoga, Legion, LOQ and ThinkBook systems. KCROC diagnoses the fault before recommending repair, with component-level board work where practical, plus screen, charging, battery, cooling and upgrade services.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": true
    },
    {
      "id": "brand-asus",
      "slug": "asus-laptop-repair-kuwait",
      "title": "ASUS Laptop Repair Kuwait",
      "description": "ASUS Republic of Gamers (ROG) and TUF laptops are powerhouses, but Kuwait's heat pushes their liquid metal and thermal paste to the limit. We specialize in ASUS thermal recovery, ROG motherboard component-level repair, and TUF series screen and battery replacements.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": true
    },
    {
      "id": "brand-acer",
      "slug": "acer-laptop-repair-kuwait",
      "title": "Acer Laptop Repair Kuwait",
      "description": "Acer Nitro and Predator gaming laptops offer great value but frequently suffer from DC charging jack failures and cooling system blockages in Kuwait. We provide comprehensive repair for Acer Aspire, Nitro, and Predator models, including motherboard diagnostics and screen replacements.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": true
    },
    {
      "id": "brand-msi",
      "slug": "msi-laptop-repair-kuwait",
      "title": "MSI Laptop Repair Kuwait",
      "description": "MSI laptops are premium gaming machines that require specialized care. In Kuwait, MSI hinges (particularly on GE and GF series) are notorious for breaking. We repair MSI chassis damage, resolve complex motherboard power faults, and provide advanced thermal repasting.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": true
    }
  ],
  "problems": [
    {
      "id": "problem-no-power",
      "slug": "laptop-wont-turn-on",
      "title": "Laptop Won't Turn On (No Power)",
      "description": "A technician-led no-power diagnostic for laptops with no lights, no fan spin, no charging response or a dead power button.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-overheating",
      "slug": "laptop-overheating-kuwait",
      "title": "Laptop Overheating Kuwait",
      "description": "Diagnostic guide for laptops thermal throttling and shutting down from extreme heat.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-black-screen",
      "slug": "laptop-black-screen-kuwait",
      "title": "Laptop Turns On But Screen is Black",
      "description": "Diagnostic guide for laptops that power on (lights/fans) but display nothing on the screen.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-liquid-spill",
      "slug": "spilled-water-on-laptop",
      "title": "Spilled Water or Coffee on Laptop",
      "description": "Emergency guide for liquid damage on laptops and MacBooks.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-not-charging",
      "slug": "laptop-plugged-in-not-charging",
      "title": "Laptop Plugged In But Not Charging",
      "description": "Troubleshooting a laptop that detects the charger but the battery percentage does not increase.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-keyboard-fail",
      "slug": "laptop-keyboard-not-working",
      "title": "Laptop Keyboard Not Working",
      "description": "Troubleshooting guide for laptops where some or all keyboard keys have stopped responding.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-wifi-fail",
      "slug": "laptop-wifi-not-connecting",
      "title": "Laptop WiFi Not Connecting or Missing",
      "description": "Diagnosis for laptops that cannot find WiFi networks, frequently drop connection, or are missing the WiFi icon entirely.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-slow",
      "slug": "laptop-running-very-slow",
      "title": "Laptop Running Extremely Slow",
      "description": "Solutions for laptops that take minutes to boot up, freeze during basic tasks, or show 100% disk usage.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-hinge-break",
      "slug": "laptop-hinge-broken",
      "title": "Laptop Hinge Broken or Splitting",
      "description": "Repair guide for laptops where the screen hinge is stiff, broken, or separating from the plastic casing.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-cracked-screen",
      "slug": "laptop-screen-cracked-kuwait",
      "title": "Laptop Screen Cracked or Shattered",
      "description": "Repair guide for laptops with a physically cracked, shattered, or spider-webbed display panel after a drop or impact.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-windows-wont-boot",
      "slug": "windows-wont-boot-kuwait",
      "title": "Windows Won't Boot or Stuck in Repair Loop",
      "description": "Diagnostic guide for laptops that get stuck on the manufacturer logo, drop into 'Preparing Automatic Repair', or loop endlessly instead of reaching the Windows desktop.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-bsod",
      "slug": "blue-screen-of-death-bsod-fix-kuwait",
      "title": "Blue Screen of Death (BSOD)",
      "description": "Diagnostic guide for laptops and PCs that crash to a blue error screen with a stop code, either occasionally or repeatedly.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-freezing-crashing",
      "slug": "computer-freezing-crashing-kuwait",
      "title": "Computer Freezing or Randomly Crashing",
      "description": "Diagnosis for laptops and PCs that freeze mid-task, require a hard restart, or reboot themselves without warning.",
      "iconKey": "",
      "popular": true,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    },
    {
      "id": "problem-malware",
      "slug": "virus-malware-removal-kuwait",
      "title": "Virus, Malware or Ransomware Infection",
      "description": "Removal service for laptops and PCs showing signs of viruses, adware, browser hijackers, or ransomware.",
      "iconKey": "",
      "popular": false,
      "noFixNoFee": false,
      "hasManyFeatures": false,
      "hasPricing": false
    }
  ],
  "caseStudies": [
    {
      "id": "case-macbook-liquid-salmiya",
      "slug": "macbook-liquid-damage-salmiya",
      "title": "MacBook Pro M2 Liquid Damage Repair — Salmiya",
      "description": "Real repair case study of a coffee-damaged MacBook Pro M2 motherboard restoration."
    },
    {
      "id": "case-rog-motherboard-hawalli",
      "slug": "asus-rog-dead-motherboard-hawalli",
      "title": "ASUS ROG Strix Dead Motherboard Recovery — Hawalli",
      "description": "Component-level restoration of a completely dead gaming laptop motherboard."
    },
    {
      "id": "case-dell-screen-kuwait-city",
      "slug": "dell-xps-screen-replacement-kuwait-city",
      "title": "Same-Day Dell XPS Screen Replacement — Kuwait City",
      "description": "Rapid turnaround logistics and OEM display replacement for a corporate client."
    }
  ],
  "locations": [
    {
      "id": "loc-hawalli",
      "slug": "hawalli",
      "title": "Hawalli Repair Center",
      "navigationPriority": 100
    },
    {
      "id": "loc-kuwait-city",
      "slug": "kuwait-city",
      "title": "Kuwait City",
      "navigationPriority": 95
    },
    {
      "id": "loc-salmiya",
      "slug": "salmiya",
      "title": "Salmiya",
      "navigationPriority": 90
    },
    {
      "id": "loc-farwaniya",
      "slug": "farwaniya",
      "title": "Farwaniya",
      "navigationPriority": 80
    },
    {
      "id": "loc-jahra",
      "slug": "jahra",
      "title": "Jahra",
      "navigationPriority": 70
    },
    {
      "id": "loc-ahmadi",
      "slug": "ahmadi",
      "title": "Ahmadi",
      "navigationPriority": 60
    },
    {
      "id": "loc-fahaheel",
      "slug": "fahaheel",
      "title": "Fahaheel",
      "navigationPriority": 55
    },
    {
      "id": "loc-mangaf",
      "slug": "mangaf",
      "title": "Mangaf",
      "navigationPriority": 50
    },
    {
      "id": "loc-abu-halifa",
      "slug": "abu-halifa",
      "title": "Abu Halifa",
      "navigationPriority": 45
    },
    {
      "id": "loc-jabriya",
      "slug": "jabriya",
      "title": "Jabriya",
      "navigationPriority": 40
    },
    {
      "id": "loc-mubarak-al-kabeer",
      "slug": "mubarak-al-kabeer",
      "title": "Mubarak Al-Kabeer",
      "navigationPriority": 35
    },
    {
      "id": "loc-fintas",
      "slug": "fintas",
      "title": "Fintas",
      "navigationPriority": 30
    },
    {
      "id": "loc-sabah-al-salem",
      "slug": "sabah-al-salem",
      "title": "Sabah Al-Salem",
      "navigationPriority": 25
    },
    {
      "id": "loc-salwa",
      "slug": "salwa",
      "title": "Salwa",
      "navigationPriority": 80
    },
    {
      "id": "loc-rumaithiya",
      "slug": "rumaithiya",
      "title": "Rumaithiya",
      "navigationPriority": 78
    },
    {
      "id": "loc-shaab",
      "slug": "shaab",
      "title": "Shaab",
      "navigationPriority": 76
    },
    {
      "id": "loc-surra",
      "slug": "surra",
      "title": "Surra",
      "navigationPriority": 74
    },
    {
      "id": "loc-khaitan",
      "slug": "khaitan",
      "title": "Khaitan",
      "navigationPriority": 72
    },
    {
      "id": "loc-riggae",
      "slug": "riggae",
      "title": "Riggae",
      "navigationPriority": 70
    },
    {
      "id": "loc-ardiya",
      "slug": "ardiya",
      "title": "Ardiya",
      "navigationPriority": 68
    },
    {
      "id": "loc-mahboula",
      "slug": "mahboula",
      "title": "Mahboula",
      "navigationPriority": 64
    },
    {
      "id": "loc-qurain",
      "slug": "qurain",
      "title": "Qurain",
      "navigationPriority": 60
    },
    {
      "id": "loc-qortuba",
      "slug": "qortuba",
      "title": "Qortuba",
      "navigationPriority": 54
    },
    {
      "id": "loc-rawda",
      "slug": "rawda",
      "title": "Rawda",
      "navigationPriority": 52
    },
    {
      "id": "loc-messila",
      "slug": "messila",
      "title": "Messila",
      "navigationPriority": 50
    },
    {
      "id": "loc-adailiya",
      "slug": "adailiya",
      "title": "Adailiya",
      "navigationPriority": 46
    }
  ],
  "blogEntries": [
    {
      "id": "blog-pc-gaming-graphics-settings-better-visuals-fps",
      "slug": "blog/pc-gaming-graphics-settings-better-visuals-fps",
      "title": "You Don’t Need Max Graphics Settings for Great PC Gaming Visuals",
      "description": "You do not need every PC graphics setting at Ultra. Learn which settings are worth keeping high for better gaming visuals without giving away unnecessary FPS.",
      "iconKey": "gaming",
      "date": "2026-10-05",
      "primaryKeyword": "PC Gaming"
    },
    {
      "id": "blog-laptop-slow-2026",
      "slug": "blog/why-is-my-laptop-so-slow-2026",
      "title": "Why Is My Laptop So Slow in 2026? 15 Causes, Tests & Fixes",
      "description": "Why is your laptop so slow in 2026? Diagnose 15 common causes including RAM, SSD/HDD, 100% disk usage, overheating, startup apps, Windows 11 and hardware faults.",
      "iconKey": "laptop",
      "date": "2026-09-26",
      "primaryKeyword": "Laptop Running Slow"
    },
    {
      "id": "blog-windows-11-100-disk-usage",
      "slug": "blog/windows-11-100-disk-usage-causes-solutions",
      "title": "Windows 11 100% Disk Usage: Causes & Solutions",
      "description": "Windows 11 100% Disk Usage? Learn the causes, safe fixes, HDD vs SSD warning signs, RAM paging, and when an SSD upgrade or KCROC diagnosis makes sense.",
      "iconKey": "shield",
      "date": "2026-09-22",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "blog-gaming-laptop-cleaning-ar",
      "slug": "blog/ar/how-often-clean-laptop-replace-thermal-paste-kuwait",
      "title": "كل كم لازم تنظف لابتوب القيمنق وتغيّر المعجون الحراري في الكويت؟",
      "description": "دليل عملي باللهجة الكويتية عن تنظيف لابتوب القيمنق وتغيير المعجون الحراري وتأثير حرارة وغبار الكويت على التبريد.",
      "iconKey": "cpu",
      "date": "2026-09-14",
      "primaryKeyword": "كل كم لازم تنظف لابتوب القيمنق وتغيّر المعجون الحراري في الكويت؟"
    },
    {
      "id": "blog-laptop-cleaning-thermal-paste-kuwait-2026",
      "slug": "blog/how-often-clean-laptop-replace-thermal-paste-kuwait",
      "title": "How Often Should You Clean Your Gaming Laptop and Replace Its Thermal Paste in Kuwait?",
      "description": "How often should you clean a gaming laptop in Kuwait? Learn practical gaming-laptop cleaning intervals, when thermal paste needs replacing, signs of dust buildup and thermal throttling, and safe cooling maintenance from KCROC.",
      "iconKey": "cpu",
      "date": "2026-09-14",
      "primaryKeyword": "gaming laptop cleaning"
    },
    {
      "id": "blog-laptop-wont-turn-on-causes-fixes",
      "slug": "blog/laptop-wont-turn-on-causes-fixes",
      "title": "Laptop Won’t Turn On? 15 Causes, Tests & What to Do Before Repair",
      "description": "Laptop won’t turn on? Learn how to diagnose charging, battery, power, RAM, BIOS, display and motherboard problems safely before bringing your laptop for repair in Kuwait.",
      "iconKey": "laptop",
      "date": "2026-09-07",
      "primaryKeyword": "laptop won't turn on"
    },
    {
      "id": "blog-laptop-temperatures-kuwait-2026",
      "slug": "blog/laptop-temperatures-kuwait-safe-cpu-gpu-temperatures",
      "title": "Laptop Temperatures in Kuwait: What Is Normal, What Is Too Hot?",
      "description": "Laptop temperatures in Kuwait: practical CPU/GPU reference ranges, 90°C explained, thermal throttling signs, manufacturer thermal limits, and a technician-led cooling diagnostic method.",
      "iconKey": "cpu",
      "date": "2026-09-01",
      "primaryKeyword": "laptop temperature"
    },
    {
      "id": "blog-gaming-pc-mistakes-2026",
      "slug": "blog/gaming-pc-mistakes-kuwait",
      "title": "10 Gaming PC Mistakes That Are Quietly Killing Your Performance (2026)",
      "description": "The most common gaming PC mistakes we see on the repair bench in Kuwait — from dried thermal paste and bad airflow to bottlenecked builds and disabled XMP — and how to fix each one.",
      "iconKey": "gaming",
      "date": "2026-08-17",
      "primaryKeyword": "Gaming PC"
    },
    {
      "id": "blog-windows-11-dumping-2026",
      "slug": "blog/10-reasons-why-people-are-dumping-windows-11",
      "title": "10 Reasons Why People Are Dumping Windows 11 (2026)",
      "description": "Windows 11 problems driving users away in 2026 — hardware limits, performance complaints, privacy, Copilot, and Windows 10's real deadline, explained by a Kuwait repair technician.",
      "iconKey": "shield",
      "date": "2026-08-16",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "blog-8gb-ram-2026",
      "slug": "blog/why-8gb-ram-is-no-longer-enough-for-windows-11",
      "title": "Is 8GB RAM Enough for Windows 11 in 2026?",
      "description": "Is 8GB RAM enough for Windows 11 in 2026? Compare 8GB, 16GB and 32GB for multitasking, gaming, memory pressure and laptop upgradeability.",
      "iconKey": "shield",
      "date": "2026-07-30",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "blog-screen-protect",
      "slug": "blog/how-to-protect-laptop-screen",
      "title": "How to Protect Your Laptop Screen from Breaking",
      "description": "A cracked laptop screen is one of the most common repairs in our Hawalli lab. Follow these habits to prevent expensive display damage.",
      "iconKey": "monitor",
      "date": "2026-07-02",
      "primaryKeyword": "Maintenance"
    },
    {
      "id": "blog-gaming-cooling",
      "slug": "blog/gaming-pc-cooling",
      "title": "Why Your Gaming PC is Overheating in Kuwait",
      "description": "Experiencing severe FPS drops in Warzone or Valorant? Cooling, drivers, power delivery and other bottlenecks can all contribute. Here is how to investigate overheating without assuming one cause.",
      "iconKey": "gaming",
      "date": "2026-06-22",
      "primaryKeyword": "Gaming"
    },
    {
      "id": "blog-laptop-repair-2026",
      "slug": "blog/laptop-repair-kuwait-2026",
      "title": "The Ultimate Guide to Laptop Repair in Kuwait (2026)",
      "description": "A broad 2026 laptop-repair guide for Kuwait covering diagnosis, power, screens, batteries, cooling, upgrades, motherboard faults, repair-versus-replacement decisions and links to specialist KCROC guides.",
      "iconKey": "laptop",
      "date": "2026-06-15",
      "primaryKeyword": "Hardware"
    },
    {
      "id": "guide-laptop-buying-ar",
      "slug": "blog/ar/laptop-buying-guide-kuwait-2026",
      "title": "دليل شراء اللابتوب في الكويت 2026: اللي ما يقوله لك البائع",
      "description": "محتار بين Intel وRyzen وRTX؟ مهندس صيانة في الكويت يشرح لك المواصفات اللي تفرق بالأداء والمواصفات اللي مجرد تسويق.",
      "iconKey": "laptop",
      "date": "",
      "primaryKeyword": "دليل شراء اللابتوب في الكويت 2026: اللي ما يقوله لك البائع"
    },
    {
      "id": "guide-intel-vs-amd",
      "slug": "blog/intel-core-ultra-vs-amd-ryzen-ai",
      "title": "Intel Core Ultra vs AMD Ryzen AI: Which Is Better?",
      "description": "Intel Core Ultra vs AMD Ryzen AI: compare CPU performance, integrated graphics, NPU features, power limits, cooling and laptop configuration before you buy.",
      "iconKey": "cpu",
      "date": "",
      "primaryKeyword": "intel core ultra vs amd ryzen ai: which is better?"
    },
    {
      "id": "guide-laptop-buying",
      "slug": "blog/laptop-buying-guide-kuwait-2026",
      "title": "Laptop Buying Guide Kuwait 2026 | Specs That Matter | KCROC",
      "description": "Laptop buying guide for Kuwait: compare CPU, RAM, SSD, GPU, cooling and upgradeability so you can choose a configuration that fits your actual workload.",
      "iconKey": "laptop",
      "date": "",
      "primaryKeyword": "laptop buying guide kuwait 2026 | specs that matter | kcroc"
    }
  ],
  "guideEntries": [
    {
      "id": "guide-windows-troubleshooting-complete-guide",
      "slug": "guides/windows-troubleshooting-complete-guide",
      "title": "Windows Troubleshooting: A Complete Guide to Diagnosing and Fixing Windows Problems",
      "description": "Windows troubleshooting guide for Windows 11 and Windows 10: triage by symptom, read stop codes, use Safe Mode, DISM and SFC, and know when it is hardware.",
      "iconKey": "shield",
      "date": "2026-10-06",
      "primaryKeyword": "Windows Troubleshooting"
    },
    {
      "id": "guide-bios-uefi-ar",
      "slug": "guides/ar/bios-uefi-recovery-kuwait",
      "title": "استرداد BIOS بعد فشل التحديث: دليل UEFI والأعطال",
      "description": "دليل لتمييز تلف فيرموير BIOS/UEFI عن أعطال الرام والطاقة واللوحة الأم، مع طرق الاسترداد الآمنة وبرمجة شريحة SPI في الكويت.",
      "iconKey": "cpu",
      "date": "2026-10-05",
      "primaryKeyword": "استرداد bios بعد فشل التحديث: دليل uefi والأعطال"
    },
    {
      "id": "guide-bios-uefi",
      "slug": "guides/bios-uefi-recovery-kuwait",
      "title": "BIOS & UEFI Troubleshooting, Update Failures & Firmware Recovery",
      "description": "A black screen after a BIOS update, a boot loop, or a system that won't POST can come from corrupted firmware — or from RAM, power, EC, or motherboard faults that only look like a BIOS problem. Covers warning signs, Secure Boot/BitLocker behavior, manufacturer recovery methods, and professional SPI/EEPROM reprogramming.",
      "iconKey": "cpu",
      "date": "2026-10-05",
      "primaryKeyword": "bios & uefi troubleshooting, update failures & firmware recovery"
    },
    {
      "id": "guide-bitlocker-recovery-key-after-bios-update",
      "slug": "guides/bitlocker-recovery-key-after-bios-update",
      "title": "Why Windows Asks for a BitLocker Recovery Key After a BIOS Update (and What to Do)",
      "description": "Windows asking for a BitLocker recovery key after a BIOS update? Learn why it happens, where to find the key, how to suspend BitLocker before firmware updates, and what to do if the key is lost.",
      "iconKey": "cpu",
      "date": "2026-10-05",
      "primaryKeyword": "BitLocker Recovery Key"
    },
    {
      "id": "guide-gaming-gpu-artifacts-repair-kuwait",
      "slug": "guides/gaming-gpu-artifacts-repair-kuwait",
      "title": "GPU Artifacting, Flickering & Black Screens in Games: Kuwait Repair Guide",
      "description": "GPU artifacting during gaming does not automatically mean the graphics card is dead. Diagnose VRAM, GPU thermals, power delivery, drivers and display-path causes before replacement. Kuwait repair guide.",
      "iconKey": "gaming",
      "date": "2026-10-01",
      "primaryKeyword": "GPU Artifacting"
    },
    {
      "id": "guide-gaming-pc-bios-failed-update-kuwait",
      "slug": "guides/gaming-pc-bios-failed-update-kuwait",
      "title": "Gaming PC Won’t Boot After a BIOS Update: Kuwait Recovery Guide",
      "description": "Gaming PC won't boot after a BIOS update? Learn how to distinguish CMOS reset, firmware recovery and motherboard repair, with a Kuwait gaming-PC repair path.",
      "iconKey": "gaming",
      "date": "2026-10-01",
      "primaryKeyword": "Gaming PC BIOS Update"
    },
    {
      "id": "guide-gaming-pc-black-screen-no-display-kuwait",
      "slug": "guides/gaming-pc-black-screen-no-display-kuwait",
      "title": "Gaming PC Black Screen / No Display After Boot: Kuwait Repair Guide",
      "description": "Gaming PC turns on but has no display? Diagnose GPU, RAM, monitor signal, BIOS, PCIe power and motherboard faults before replacing the graphics card. Kuwait repair guide.",
      "iconKey": "gaming",
      "date": "2026-10-01",
      "primaryKeyword": "Gaming PC No Display"
    },
    {
      "id": "guide-gaming-pc-not-turning-on-kuwait",
      "slug": "guides/gaming-pc-not-turning-on-kuwait",
      "title": "Gaming PC Won’t Turn On? Kuwait Troubleshooting & Repair Guide",
      "description": "Gaming PC won't turn on in Kuwait? Use a safe power-path checklist for PSU, motherboard, GPU, front-panel, short-circuit and BIOS problems, then know when professional diagnosis is appropriate.",
      "iconKey": "gaming",
      "date": "2026-10-01",
      "primaryKeyword": "Gaming PC Won't Turn On"
    },
    {
      "id": "guide-gaming-pc-optimization-2026",
      "slug": "guides/gaming-pc-optimization-2026",
      "title": "Gaming PC Optimization 2026: The Evidence-Based Guide to More FPS, Better 1% Lows & Lower Latency",
      "description": "A measurement-first gaming PC optimization guide for 2026 covering FPS, 1% lows, frame-time, CPU/GPU bottlenecks, RAM, thermals, ReBAR, VRR, Reflex, Windows settings and safe tuning.",
      "iconKey": "gaming",
      "date": "2026-10-01",
      "primaryKeyword": "Gaming PC Optimization"
    },
    {
      "id": "guide-gaming-pc-random-shutdown-kuwait",
      "slug": "guides/gaming-pc-random-shutdown-kuwait",
      "title": "Gaming PC Shuts Down While Gaming? PSU, Heat & Motherboard Diagnosis",
      "description": "Gaming PC randomly shuts down while gaming? Diagnose PSU output, CPU/GPU temperatures, VRM power, cooling and stability instead of replacing parts blindly. Kuwait repair guide.",
      "iconKey": "gaming",
      "date": "2026-10-01",
      "primaryKeyword": "Gaming PC Shuts Down"
    },
    {
      "id": "guide-battery",
      "slug": "guides/laptop-battery-warning-signs",
      "title": "Laptop Battery Warning Signs: 15+ Signs & Tests",
      "description": "A practical laptop battery authority guide covering 15+ warning signs, Windows 11 and Mac battery-health checks, swollen-battery safety, diagnosis, and replacement decisions.",
      "iconKey": "battery",
      "date": "2026-09-30T00:00:00+03:00",
      "primaryKeyword": "laptop battery warning signs: 15+ signs & tests"
    },
    {
      "id": "guide-laptop-overheating",
      "slug": "guides/why-is-my-laptop-so-hot",
      "title": "Why Is My Laptop So Hot? Universal Overheating Causes, Diagnosis & Fixes",
      "description": "A universal, platform-independent laptop overheating guide covering workload, airflow, dust, fan faults, thermal throttling, temperature interpretation, safe checks and repair warning signs.",
      "iconKey": "laptop",
      "date": "2026-09-30T00:00:00+03:00",
      "primaryKeyword": "why is my laptop so hot? universal overheating causes, diagnosis & fixes"
    },
    {
      "id": "guide-dpc-latency-gaming-stutter",
      "slug": "guides/dpc-latency-gaming-stutter",
      "title": "DPC Latency and Gaming Stutter: How Driver Interrupt Delays Can Affect Smoothness",
      "description": "DPC latency gaming guide: understand ISR and DPC activity, recognize driver-related hitch patterns, and use evidence before changing device drivers or Windows settings.",
      "iconKey": "gaming",
      "date": "2026-09-29",
      "primaryKeyword": "DPC Latency"
    },
    {
      "id": "guide-shader-compilation-stutter-windows",
      "slug": "guides/shader-compilation-stutter-windows",
      "title": "Shader Compilation Stutter in PC Games: Why High FPS Can Still Hitch",
      "description": "Shader compilation stutter explained: why PC games can hitch when new effects appear, how driver updates affect caches, and what to test before changing Windows settings.",
      "iconKey": "shield",
      "date": "2026-09-29",
      "primaryKeyword": "Shader Compilation"
    },
    {
      "id": "guide-ssd-not-detected-windows-11",
      "slug": "guides/ssd-not-detected-windows-11",
      "title": "SSD Not Detected in Windows 11: Complete Diagnosis & Fix Guide",
      "description": "SSD not detected in Windows 11? Check BIOS/UEFI, Disk Management, drive letters, controllers, compatibility and hardware health without risking your data.",
      "iconKey": "shield",
      "date": "2026-09-29",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-windows-11-100-cpu-usage",
      "slug": "guides/windows-11-100-cpu-usage",
      "title": "Windows 11 100% CPU Usage: Causes, Diagnosis & Safe Fixes",
      "description": "Windows 11 100% CPU usage? Find the process, check startup apps, thermals, updates and malware, and know when hardware diagnosis is needed.",
      "iconKey": "cpu",
      "date": "2026-09-29",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-windows-11-connected-to-wifi-no-internet",
      "slug": "guides/windows-11-connected-to-wifi-but-no-internet",
      "title": "Connected to Wi-Fi but No Internet in Windows 11: Complete Fix Guide",
      "description": "Connected to Wi-Fi but no internet in Windows 11? Diagnose router, DNS, DHCP, VPN, proxy, Windows and adapter problems step by step.",
      "iconKey": "shield",
      "date": "2026-09-29",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-windows-11-update-problems",
      "slug": "guides/windows-11-update-problems",
      "title": "Windows 11 Update Problems: Errors, Failed Installs & Safe Fixes",
      "description": "Windows 11 Update problems? Diagnose failed installs, error codes, restart loops, storage space, drivers and update recovery safely.",
      "iconKey": "shield",
      "date": "2026-09-29",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-windows-11-wifi-keeps-disconnecting",
      "slug": "guides/windows-11-wifi-keeps-disconnecting",
      "title": "Windows 11 Wi-Fi Keeps Disconnecting: Complete Fix Guide for 2026",
      "description": "Windows 11 Wi-Fi keeps disconnecting? Diagnose adapter, driver, power management, router, interference, VPN and Windows causes step by step.",
      "iconKey": "shield",
      "date": "2026-09-29",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-windows-gaming-frame-time-stutter",
      "slug": "guides/windows-gaming-frame-time-stutter",
      "title": "Gaming Stutter With High FPS: How to Read Frame-Time in Windows 11",
      "description": "Gaming stutter with high FPS? Learn how frame-time spikes work, how to reproduce hitching, and how to separate rendering stutter from input, network, CPU, GPU and thermal problems.",
      "iconKey": "gaming",
      "date": "2026-09-29",
      "primaryKeyword": "Gaming Stutter"
    },
    {
      "id": "guide-windows-gaming-performance-pillar",
      "slug": "guides/windows-gaming-performance-stutter-fix",
      "title": "Windows 11 Gaming Stutter & FPS Drops: Complete Fix Guide for 2026",
      "description": "Gaming stuttering despite high FPS? Diagnose frame-time spikes, shaders, Game Bar, DPC latency, drivers, RAM, GPU limits and thermal throttling in Windows 11.",
      "iconKey": "gaming",
      "date": "2026-09-29",
      "primaryKeyword": "Windows 11 Gaming"
    },
    {
      "id": "guide-dell-laptop-overheating",
      "slug": "guides/dell-laptop-overheating",
      "title": "Dell Laptop Overheating Guide",
      "description": "Step-by-step thermal troubleshooting for Dell laptops, including Inspiron, Latitude, Vostro, XPS, Precision, G Series, and Alienware families.",
      "iconKey": "cpu",
      "date": "2026-09-27T00:00:00+03:00",
      "primaryKeyword": "dell laptop overheating guide"
    },
    {
      "id": "guide-laptop-wont-turn-on-2026",
      "slug": "guides/laptop-wont-turn-on",
      "title": "Laptop Won't Turn On? Complete Troubleshooting Guide",
      "description": "Laptop won't turn on? Follow a safe step-by-step diagnosis for no power, no charging light, black screen, battery, charger, USB-C and motherboard faults, with Kuwait-specific repair guidance from KCROC.",
      "iconKey": "laptop",
      "date": "2026-09-27",
      "primaryKeyword": "Laptop Won't Turn On"
    },
    {
      "id": "guide-windows-10-eos",
      "slug": "guides/windows-10-end-of-support",
      "title": "Windows 10 End of Support: What It Means and What to Do in 2026",
      "description": "Windows 10 support ended on October 14, 2025. Understand Consumer ESU through October 2027, Windows 11 eligibility, and when to upgrade, repair, replace, or switch operating systems.",
      "iconKey": "shield",
      "date": "2026-09-09T00:00:00+03:00",
      "primaryKeyword": "windows 10 end of support: what it means and what to do in 2026"
    },
    {
      "id": "guide-windows-11-settings-tweaks-2026",
      "slug": "guides/windows-11-settings-tweaks",
      "title": "18 Windows 11 Settings Worth Changing for Privacy, Speed & Better Control",
      "description": "Review 18 Windows 11 settings for privacy, startup speed, battery life, gaming and security. Practical advice from KCROC computer technicians in Kuwait.",
      "iconKey": "shield",
      "date": "2026-09-08",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-windows-11-background-services-audit-2026",
      "slug": "guides/windows-11-background-services-audit",
      "title": "Windows 11 Background Services You Can Audit in 2026",
      "description": "Windows 11 background services: understand WHESVC, DiagTrack, SysMain and MapsBroker, when to investigate them, and why measured troubleshooting is safer than random debloating.",
      "iconKey": "shield",
      "date": "2026-09-05",
      "primaryKeyword": "Windows 11"
    },
    {
      "id": "guide-gamebar-presence-writer",
      "slug": "guides/gamebar-presence-writer-fix",
      "title": "GameBarPresenceWriter.exe: What It Does, How to Fix Performance Issues, and How to Disable It",
      "description": "What is GameBarPresenceWriter.exe? A measured, evidence-first guide covering Game Bar stutter, background capture activity, the advanced Game DVR registry method, and safer rollback-first troubleshooting.",
      "iconKey": "gaming",
      "date": "",
      "primaryKeyword": "gamebarpresencewriter.exe: what it does, how to fix performance issues, and how to disable it"
    }
  ],
  "newsEntries": [
    {
      "id": "news-microsoft-windows-surface-event-october-7-2026",
      "slug": "news/microsoft-windows-surface-event-october-7-2026",
      "title": "Microsoft Windows & Surface Event on October 7, 2026: What to Expect",
      "description": "Microsoft's October 7 Windows and Surface event puts local AI PCs, Surface hardware and NVIDIA RTX Spark technology in focus. Here is what is confirmed, what remains unknown, and what buyers in Kuwait should watch.",
      "iconKey": "shield",
      "date": "2026-10-03",
      "primaryKeyword": "Microsoft Surface"
    },
    {
      "id": "news-windows-11-26h2-iso-released",
      "slug": "news/windows-11-26h2-iso-released",
      "title": "Windows 11 26H2 ISO Is Now Available — What PC Users Should Know Before Installing",
      "description": "Windows 11 26H2 ISO is now available. Learn the official download options, requirements, upgrade vs clean install paths, installation fixes, and post-install checks.",
      "iconKey": "shield",
      "date": "2026-09-30",
      "primaryKeyword": "Windows 11 26H2"
    }
  ]
} as const;
