import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { KCROC_GRAPH } from '../src/data/graph';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outPath = path.resolve(__dirname, '../src/data/seoGraph.generated.ts');

const base = (e: any) => ({ id: e.id, entityType: e.entityType, isActive: e.isActive, title: e.title, slug: e.slug, seo: e.seo });
const pickFaq = (f: any) => ({ id: f.id, title: f.title, question: f.question, answer: f.answer });

const routableEntities = (KCROC_GRAPH.routableEntities ?? []).map((e: any) => {
  const b = base(e);
  switch (e.entityType) {
    case 'Business':
      return { ...b, legalName: e.legalName, logoUrl: e.logoUrl, telephone: e.telephone, email: e.email, websiteUrl: e.websiteUrl, priceRange: e.priceRange, addressRegion: e.addressRegion, schemaOpeningHours: e.schemaOpeningHours, socialLinks: e.socialLinks };
    case 'Service':
      return { ...b, description: e.description, pricing: e.pricing, faqs: e.faqs };
    case 'Brand':
      return { ...b, brandName: e.brandName, officialWebsite: e.officialWebsite, pricing: e.pricing, commonIssues: e.commonIssues ?? [], faqs: e.faqs };
    case 'Problem':
      return { ...b, description: e.description, intro: e.intro, symptom: e.symptom, causes: e.causes ?? [], diagnosticSteps: e.diagnosticSteps ?? [], technicianMethod: e.technicianMethod ?? [], solution: e.solution, kuwaitContext: e.kuwaitContext ?? [], faqs: e.faqs ?? [], primaryKeyword: e.primaryKeyword, secondaryKeywords: e.secondaryKeywords ?? [], featuredImage: e.featuredImage };
    case 'FAQ':
      return { ...b, answer: e.answer };
    case 'CaseStudy':
      return { ...b, description: e.description, publishDate: e.publishDate, authorId: e.authorId, brandId: e.brandId, serviceIds: e.serviceIds ?? [], problemIds: e.problemIds ?? [], locationId: e.locationId, deviceModel: e.deviceModel, device: e.device, symptom: e.symptom, diagnosis: e.diagnosis, repair: e.repair, outcome: e.outcome, repairDuration: e.repairDuration, timeToRepair: e.timeToRepair, costVsReplacement: e.costVsReplacement, testingPerformed: e.testingPerformed ?? [], location: e.location, featuredImage: e.featuredImage };
    case 'Location':
      return { ...b, coords: e.coords, serviceAreas: e.serviceAreas ?? [] };
    case 'WebPage':
      return { ...b, description: e.description, featuredFAQIds: e.featuredFAQIds ?? [], articleSection: e.articleSection, authorUrl: e.authorUrl, datePublished: e.datePublished, dateModified: e.dateModified };
    default:
      return b;
  }
});

const faqEntities = (KCROC_GRAPH.faqs ?? []).map((f: any) => ({ id: f.id, title: f.title, answer: f.answer }));
const related = {
  services: (KCROC_GRAPH.services ?? []).map((e: any) => ({ id: e.id, title: e.title, description: e.description })),
  brands: (KCROC_GRAPH.brands ?? []).map((e: any) => ({ id: e.id, slug: e.slug, brandName: e.brandName, title: e.title, officialWebsite: e.officialWebsite, seo: e.seo })),
  problems: (KCROC_GRAPH.problems ?? []).map((e: any) => ({ id: e.id, title: e.title })),
  locations: (KCROC_GRAPH.locations ?? []).map((e: any) => ({ id: e.id, title: e.title, coords: e.coords, serviceAreas: e.serviceAreas ?? [] }))
};

const business = KCROC_GRAPH.business ? {
  websiteUrl: KCROC_GRAPH.business.websiteUrl,
  logoUrl: KCROC_GRAPH.business.logoUrl,
  legalName: KCROC_GRAPH.business.legalName,
  telephone: KCROC_GRAPH.business.telephone,
  email: KCROC_GRAPH.business.email,
  priceRange: KCROC_GRAPH.business.priceRange,
  addressRegion: KCROC_GRAPH.business.addressRegion,
  schemaOpeningHours: KCROC_GRAPH.business.schemaOpeningHours,
  socialLinks: KCROC_GRAPH.business.socialLinks
} : null;

const banner = `// AUTO-GENERATED by scripts/generate-seo-data.ts — DO NOT EDIT BY HAND.\n// Build-time SEO projection of graph.ts. graph.ts remains the source of truth.\n`;
const output = `${banner}\nexport const SEO_GRAPH = ${JSON.stringify({ routableEntities, faqs: faqEntities, business, related }, null, 2)} as const;\n`;
fs.writeFileSync(outPath, output, 'utf8');
console.log(`Generated ${path.relative(process.cwd(), outPath)} (${(output.length / 1024).toFixed(1)} KB)`);
