// File: app/frontend/scripts/generate-nav-data.ts
//
// WHY THIS EXISTS:
// src/data/graph.ts is a single ~190KB module containing every service,
// FAQ, blog post, location, and case study on the site. Header.tsx and
// Footer.tsx render on every route, and previously imported KCROC_GRAPH
// directly just to read a handful of small fields (business phone/logo,
// footer links, trust badges) plus build the mega-menu (services, brands,
// problems, case studies). Because bundlers can't tree-shake properties out
// of a big object literal at runtime, that pulled the ENTIRE graph into the
// main entry chunk on every single page load.
//
// This script runs before dev/build and extracts only the small set of
// fields the header/footer/nav actually use into a generated, lightweight
// module. graph.ts remains the single source of truth — this file is
// regenerated from it automatically, so there's no risk of drift.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { KCROC_GRAPH } from '../src/data/graph';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outPath = path.resolve(__dirname, '../src/data/navGraph.generated.ts');

type NavEntitySource = {
  id: string;
  slug?: string;
  title?: string;
  name?: string;
  description?: string;
  iconKey?: string;
  popular?: boolean;
  warranty?: { noFixNoFee?: boolean };
  coreFeatures?: unknown[];
  pricing?: unknown;
};

const slimEntity = (e: NavEntitySource) => ({
  id: e.id,
  slug: e.slug ?? '',
  title: e.title ?? e.name ?? 'Unknown',
  description: e.description ?? '',
  iconKey: e.iconKey ?? '',
  popular: !!e.popular,
  noFixNoFee: !!e.warranty?.noFixNoFee,
  hasManyFeatures: (e.coreFeatures?.length ?? 0) > 3,
  hasPricing: !!e.pricing,
});

const slimCaseStudy = (e: NavEntitySource) => ({
  id: e.id,
  slug: e.slug ?? '',
  title: e.title ?? 'Unknown',
});

const navData = {
  // The Business entity itself is small (~600 bytes) — Header/Footer need
  // most of its fields (phone, logo, socials, address, rating, hours), so
  // it's included wholesale rather than field-by-field.
  business: KCROC_GRAPH.business ?? null,
  footer: KCROC_GRAPH.footer?.links ?? null,
  trustBadges: (KCROC_GRAPH.trustBadges ?? []).map((b) => ({
    id: b.id,
    title: b.title,
    iconKey: b.iconKey,
  })),
  services: (KCROC_GRAPH.services ?? []).map(slimEntity),
  brands: (KCROC_GRAPH.brands ?? []).map(slimEntity),
  problems: (KCROC_GRAPH.problems ?? []).map(slimEntity),
  caseStudies: (KCROC_GRAPH.caseStudies ?? []).map(slimCaseStudy),
};

const banner = `// File: app/frontend/src/data/navGraph.generated.ts
// 🚀 AUTO-GENERATED by scripts/generate-nav-data.ts — DO NOT EDIT BY HAND.
// Regenerated automatically on every "dev" and "build" run from src/data/graph.ts.
// This is a deliberately slim subset (nav-relevant fields only) so that
// Header/Footer/NavigationCompiler — which render on every route — don't
// pull the full knowledge graph into the main entry bundle.
`;

const fileContents = `${banner}
export const NAV_GRAPH = ${JSON.stringify(navData, null, 2)} as const;
`;

fs.writeFileSync(outPath, fileContents, 'utf-8');
console.log(`✅ Generated ${path.relative(process.cwd(), outPath)} (${(fileContents.length / 1024).toFixed(1)} KB) from graph.ts`);
