// File: src/constants/galleryData.ts

export const galleryCategories = [
  "All", 
  "Workshop & Team", 
  "Custom PC Builds", 
  "Laptop Repairs", 
  "Upgrades & SSDs"
];

export const galleryImages = [
  // ─── WORKSHOP & TEAM ─────────────────────────────────────────────
  { src: '/images/kcroc-al-mullah-complex-hawalli-exterior.jpg.webp', alt: 'Exterior daytime view of KCROC Al Mullah Complex', category: 'Workshop & Team' },
  { src: '/images/kcroc-al-mullah-complex-hawalli-night-view.webp', alt: 'Nighttime street view of KCROC Al Mullah Complex', category: 'Workshop & Team' },
  { src: '/images/kcroc-al-mullah-complex-basement-shop-entrance.webp', alt: 'Entrance to Basement Shop 19 for KCROC', category: 'Workshop & Team' },
  { src: '/images/KCROC-commercial-Complex-view-dusk.webp', alt: 'Dusk view of the commercial district where KCROC operates', category: 'Workshop & Team' },
  { src: '/images/shop-photo.webp', alt: 'Inside the KCROC professional computer repair workshop', category: 'Workshop & Team' },
  { src: '/images/kcroc-imran-natiq-laptop-repair-workshop-owner.webp', alt: 'Imran Natiq, leading IT specialist and owner', category: 'Workshop & Team' },
  { src: '/images/kcroc-team-member-imran-hat-fun.webp', alt: 'KCROC team member having fun at the workshop', category: 'Workshop & Team' },
  { src: '/images/kcroc-lead-technician-laptop-repair-workbench.webp', alt: 'Lead technician diagnosing a motherboard', category: 'Workshop & Team' },
  { src: '/images/kcroc-technicians-laptop-repair-workbench.webp', alt: 'Team of IT technicians actively repairing laptops', category: 'Workshop & Team' },
  { src: '/images/kcroc-computer-repair-technician-team.webp', alt: 'KCROC computer repair technician team', category: 'Workshop & Team' },
  { src: '/images/kcroc-laptop-repair-parts-inventory-shelves.webp', alt: 'Inventory shelves stocked with laptop parts', category: 'Workshop & Team' },
  
  // ─── CUSTOM PC BUILDS ────────────────────────────────────────────
  { src: '/images/custom-water-cooled-gaming-pc-build.webp', alt: 'High-end custom gaming PC with liquid cooling', category: 'Custom PC Builds' },
  { src: '/images/asus-rog-gaming-pc-rgb-case-build.webp', alt: 'Premium ASUS ROG custom gaming PC build', category: 'Custom PC Builds' },
  { src: '/images/custom-gaming-pc-build-rgb-lighting.webp', alt: 'Custom desktop gaming PC with synchronized RGB', category: 'Custom PC Builds' },
  { src: '/images/geforce-rtx-gaming-pc-rgb-lighting.webp', alt: 'Gaming PC build featuring a GeForce RTX card', category: 'Custom PC Builds' },
  { src: '/images/custom-gaming-pc-msi-gpu-intel-cooler-build.webp', alt: 'Gaming rig assembly featuring an MSI graphics card', category: 'Custom PC Builds' },
  { src: '/images/custom-pc-build-msi-motherboard-thermaltake-cooler.webp', alt: 'PC build with MSI motherboard and Thermaltake cooler', category: 'Custom PC Builds' },
  { src: '/images/gaming-pc-deepcool-aio-liquid-cooler-installation.webp', alt: 'Installation of a DeepCool AIO liquid CPU cooler', category: 'Custom PC Builds' },
  { src: '/images/custom-desktop-pc-msi-gpu-darkflash-cooler.webp', alt: 'Custom desktop build with Darkflash cooling', category: 'Custom PC Builds' },
  { src: '/images/asus-rog-custom-pc-sleeved-cables.webp', alt: 'Professional cable management using white sleeved cables', category: 'Custom PC Builds' },
  { src: '/images/custom-gaming-pc-teardown-and-diagnostics-workbench.webp', alt: 'Gaming PC tower opened on the diagnostics workbench', category: 'Custom PC Builds' },
  { src: '/images/windows-11-operating-system-installation-gaming-pc.webp', alt: 'Installing Windows 11 on a fresh gaming PC build', category: 'Custom PC Builds' },
  
  // ─── LAPTOP REPAIRS ──────────────────────────────────────────────
  { src: '/images/laptop repair.webp', alt: 'Professional laptop hardware repair services', category: 'Laptop Repairs' },
  { src: '/images/motherboard repair.webp', alt: 'Precision chip-level motherboard repair', category: 'Laptop Repairs' },
  { src: '/images/apple-macbook-logic-board-and-fan-repair.webp', alt: 'Exposed Apple MacBook logic board and cooling fan', category: 'Laptop Repairs' },
  { src: '/images/technician-holding-opened-macbook-for-repair.webp', alt: 'Technician inspecting an opened MacBook', category: 'Laptop Repairs' },
  { src: '/images/macbook-internal-battery-Swollen replacement.webp', alt: 'Removing a dangerously swollen MacBook battery', category: 'Laptop Repairs' },
  { src: '/images/macbook-internal-battery-Swollen replacement (1).webp', alt: 'MacBook internal battery replacement process', category: 'Laptop Repairs' },
  { src: '/images/macbook-internal-battery-replacement-service.webp', alt: 'Standard MacBook internal battery replacement', category: 'Laptop Repairs' },
  { src: '/images/macbook-internal-battery-hardware-repair.webp', alt: 'MacBook internal hardware repair diagnostics', category: 'Laptop Repairs' },
  { src: '/images/xpanded-macbook-pro-battery-removal.webp', alt: 'Expanded MacBook Pro battery removal', category: 'Laptop Repairs' },
  { src: '/images/hp-notebook-battery-replacement.webp', alt: 'HP notebook internal battery replacement', category: 'Laptop Repairs' },
  { src: '/images/hp-ht03xl-laptop-battery-replacement.webp', alt: 'Installing a brand new HP HT03XL laptop battery', category: 'Laptop Repairs' },
  { src: '/images/hp-laptop-battery-replacement-service.webp', alt: 'HP laptop battery replacement service', category: 'Laptop Repairs' },
  { src: '/images/getac-laptop-rechargeable-battery-replacement.webp', alt: 'Getac laptop rechargeable battery replacement', category: 'Laptop Repairs' },
  { src: '/images/broken-laptop-hinge-plastic-chassis-damage.webp', alt: 'Repairing severe physical damage to a laptop hinge', category: 'Laptop Repairs' },
  { src: '/images/laptop-screen-bezel-and-hinge-fabrication.webp', alt: 'Laptop screen bezel and hinge fabrication', category: 'Laptop Repairs' },
  { src: '/images/laptop-copper-heatsink-removal-motherboard.webp', alt: 'Removing a copper heatsink from a laptop motherboard', category: 'Laptop Repairs' },
  { src: '/images/laptop-copper-heatsink-thermal-repair.jpg.webp', alt: 'Laptop copper heatsink thermal repair', category: 'Laptop Repairs' },
  { src: '/images/laptop-copper-heatsink-with-dried-thermal-paste.webp', alt: 'Laptop copper heatsink with dried thermal paste', category: 'Laptop Repairs' },
  { src: '/images/laptop-thermal-paste-application-service.jpg.webp', alt: 'Professional laptop thermal paste application service', category: 'Laptop Repairs' },
  { src: '/images/arctic-mx6-thermal-paste-application-laptop-motherboard.webp', alt: 'Applying Arctic MX-6 thermal paste to a motherboard', category: 'Laptop Repairs' },
  { src: '/images/clogged-laptop-cooling-fan-dust-cleaning.webp', alt: 'Deep cleaning a severely dust-clogged laptop fan', category: 'Laptop Repairs' },
  { src: '/images/clogged-dusty-laptop-cooling-fan-cleaning.webp', alt: 'Clogged dusty laptop cooling fan cleaning process', category: 'Laptop Repairs' },
  { src: '/images/laptop-motherboard-dusty-fan-and-wifi-card.webp', alt: 'Dusty laptop cooling fan and WiFi card inspection', category: 'Laptop Repairs' },
  { src: '/images/dual-laptop-cooling-fan-assembly-inspection.webp', alt: 'Dual laptop cooling fan assembly inspection', category: 'Laptop Repairs' },
  { src: '/images/dusty-laptop-cooling-fans-replacement.webp', alt: 'Dusty laptop cooling fans replacement', category: 'Laptop Repairs' },
  { src: '/images/new-laptop-cooling-fan-assembly-replacement.webp', alt: 'New laptop cooling fan assembly replacement', category: 'Laptop Repairs' },
  { src: '/images/aptop-cooling-fan-replacements.webp', alt: 'Laptop cooling fan replacements', category: 'Laptop Repairs' },
  { src: '/images/hp-probook-windows-11-laptop-repair.webp', alt: 'HP ProBook Windows 11 laptop repair', category: 'Laptop Repairs' },
  { src: '/images/hp-laptop-internal-hardware-diagnostics-teardown.webp', alt: 'HP laptop internal hardware diagnostics teardown', category: 'Laptop Repairs' },
  { src: '/images/dell-laptop-internal-hardware-teardown.webp', alt: 'Dell laptop internal hardware teardown', category: 'Laptop Repairs' },
  { src: '/images/dell-laptop-open-chassis-hardware-repair.webp', alt: 'Dell laptop open chassis hardware repair', category: 'Laptop Repairs' },
  { src: '/images/dell-latitude-laptop-bottom-chassis-inspection.webp', alt: 'Dell Latitude laptop bottom chassis inspection', category: 'Laptop Repairs' },
  { src: '/images/dell-laptop-windows-operating-system-installation.webp', alt: 'Dell laptop Windows operating system installation', category: 'Laptop Repairs' },
  { src: '/images/toshiba-laptop-windows-os-software-diagnostics.webp', alt: 'Toshiba laptop Windows OS software diagnostics', category: 'Laptop Repairs' },
  { src: '/images/razer-laptop-blue-screen-of-death-bsod-error.webp', alt: 'Razer laptop Blue Screen of Death (BSOD) error', category: 'Laptop Repairs' },
  { src: '/images/gaming-laptop-dual-fan-motherboard-diagnostics.jpg.webp', alt: 'Gaming laptop dual fan motherboard diagnostics', category: 'Laptop Repairs' },
  { src: '/images/msi-gaming-laptop-and-gpu-repair-workstation.jpg.webp', alt: 'MSI gaming laptop and GPU repair workstation', category: 'Laptop Repairs' },
  { src: '/images/lenovo-ideacentre-all-in-one-desktop-repair.webp', alt: 'Lenovo IdeaCentre All-in-One desktop repair', category: 'Laptop Repairs' },
  { src: '/images/hp-all-in-one-desktop-pc-hardware-repair.webp', alt: 'HP All-in-One desktop PC hardware repair', category: 'Laptop Repairs' },
  { src: '/images/laptop-spare-parts-screen-battery-keyboard-fans.webp', alt: 'Laptop spare parts, screen, battery, keyboard, and fans', category: 'Laptop Repairs' },

  // ─── UPGRADES & SSDS ─────────────────────────────────────────────
  { src: '/images/8gb-ddr4-ram-memory-upgrade.jpg.webp', alt: 'Upgrading laptop performance with an 8GB DDR4 RAM', category: 'Upgrades & SSDs' },
  { src: '/images/installing-sk-hynix-8gb-ddr4-ram.webp', alt: 'Technician installing an SK hynix 8GB DDR4 RAM stick', category: 'Upgrades & SSDs' },
  { src: '/images/sk-hynix-8gb-ddr4-laptop-ram-memory.webp', alt: 'SK hynix 8GB DDR4 laptop RAM memory', category: 'Upgrades & SSDs' },
  { src: '/images/sk-hynix-pc3l-laptop-ram-memory-upgrade.webp', alt: 'SK hynix PC3L laptop RAM memory upgrade', category: 'Upgrades & SSDs' },
  { src: '/images/wd-black-sn850-1tb-nvme-ssd-upgrade.webp', alt: 'Western Digital WD_BLACK SN850 1TB NVMe SSD', category: 'Upgrades & SSDs' },
  { src: '/images/samsung-960-evo-nvme-m2-ssd-250gb.webp', alt: 'Samsung 960 EVO NVMe M.2 SSD installation', category: 'Upgrades & SSDs' },
  { src: '/images/samsung-ssd-laptop-upgrade-kuwait.jpg.webp', alt: 'Samsung SSD laptop upgrade in Kuwait', category: 'Upgrades & SSDs' },
  { src: '/images/kioxia-128gb-m2-ssd-laptop-storage-upgrade.webp', alt: 'Kioxia 128GB M.2 SSD laptop storage upgrade', category: 'Upgrades & SSDs' },
  { src: '/images/micron-m2-nvme-ssd-laptop-storage.webp', alt: 'Micron M.2 NVMe SSD laptop storage', category: 'Upgrades & SSDs' },
  { src: '/images/lexar-nm620-m2-nvme-ssd-installation.webp', alt: 'Lexar NM620 M.2 NVMe SSD installation', category: 'Upgrades & SSDs' },
  { src: '/images/lexar-ssd-installation-laptop-internals.jpg.webp', alt: 'Lexar SSD installation inside laptop internals', category: 'Upgrades & SSDs' },
  { src: '/images/lexar-256gb-sata-ssd-laptop-upgrade.webp', alt: 'Lexar 256GB SATA SSD laptop upgrade', category: 'Upgrades & SSDs' },
  { src: '/images/orsair-mp600-core-xt-nvme-ssd-upgrade.webp', alt: 'Corsair MP600 Core XT NVMe SSD upgrade', category: 'Upgrades & SSDs' },
  { src: '/images/m2-nvme-ssd-motherboard-installation.jpg.webp', alt: 'M.2 NVMe SSD motherboard installation', category: 'Upgrades & SSDs' },
  { src: '/images/new-m2-nvme-ssd-replacement-part.jpg.webp', alt: 'New M.2 NVMe SSD replacement part', category: 'Upgrades & SSDs' },
  { src: '/images/seagate-1tb-mobile-hdd-laptop-hard-drive.webp', alt: 'Seagate 1TB mobile HDD laptop hard drive', category: 'Upgrades & SSDs' },
  { src: '/images/laptop-sata-2nd-hdd-caddy-9-5mm.webp', alt: 'Laptop SATA 2nd HDD caddy 9.5mm', category: 'Upgrades & SSDs' },
  { src: '/images/zotac-gaming-graphics-card-gpu-upgrade.webp', alt: 'Zotac Gaming graphics card GPU upgrade', category: 'Upgrades & SSDs' },
  { src: '/images/technician-holding-zotac-gaming-graphics-card.webp', alt: 'Technician holding Zotac Gaming graphics card', category: 'Upgrades & SSDs' },
  { src: '/images/intel-core-i9-13900k-cpu-asus-rog-motherboard.webp', alt: 'Intel Core i9-13900K processor in ASUS motherboard', category: 'Upgrades & SSDs' },
  { src: '/images/amd-ryzen-7-cpu-motherboard-installation.webp', alt: 'AMD Ryzen 7 CPU motherboard installation', category: 'Upgrades & SSDs' },
  { src: '/images/intel-core-i7-14th-gen-cpu-upgrade.webp', alt: 'Intel Core i7 14th gen CPU upgrade', category: 'Upgrades & SSDs' },
  { src: '/images/intel-stock-cpu-cooler-heatsink-replacement.webp', alt: 'Intel stock CPU cooler heatsink replacement', category: 'Upgrades & SSDs' },
  { src: '/images/intel-wifi-card-laptop-motherboard-repair.webp', alt: 'Intel WiFi card laptop motherboard repair', category: 'Upgrades & SSDs' },
  { src: '/images/intel-8265ngw-dual-band-wireless-wifi-card.webp', alt: 'Intel 8265NGW dual band wireless WiFi card', category: 'Upgrades & SSDs' },
  { src: '/images/intel-dual-band-wireless-card-installation.webp', alt: 'Intel dual band wireless card installation', category: 'Upgrades & SSDs' },
  { src: '/images/laptop-wifi-network-card.webp', alt: 'Laptop WiFi network card', category: 'Upgrades & SSDs' },
  { src: '/images/laptop-wifi-network-card-replacement.webp', alt: 'Laptop WiFi network card replacement', category: 'Upgrades & SSDs' },
  { src: '/images/laptop-wireless-network-card-replacement.webp', alt: 'Laptop wireless network card replacement', category: 'Upgrades & SSDs' },
  { src: '/images/asus-rog-motherboard-vrm-cooling-fan.webp', alt: 'ASUS ROG motherboard VRM cooling fan', category: 'Upgrades & SSDs' },
  { src: '/images/gigabyte-aorus-motherboard-cpu-thermal-paste-inspection.webp', alt: 'Gigabyte Aorus motherboard CPU thermal paste inspection', category: 'Upgrades & SSDs' },
  { src: '/images/applying-thermal-grizzly-kryonaut-extreme-paste.webp', alt: 'Applying Thermal Grizzly Kryonaut Extreme paste', category: 'Upgrades & SSDs' },
  { src: '/images/thermal-grizzly-kryonaut-extreme-syringe.webp', alt: 'Thermal Grizzly Kryonaut Extreme syringe', category: 'Upgrades & SSDs' },
  { src: '/images/thermal-grizzly-kryonaut-extreme-packaging.webp', alt: 'Thermal Grizzly Kryonaut Extreme packaging', category: 'Upgrades & SSDs' },
  { src: '/images/corsair-tm30-performance-thermal-paste.webp', alt: 'Corsair TM30 performance thermal paste', category: 'Upgrades & SSDs' },
  { src: '/images/m12-high-performance-thermal-paste-jar.webp', alt: 'M12 high-performance thermal paste jar', category: 'Upgrades & SSDs' },
  { src: '/images/nzxt-f120-rgb-core-case-fan.webp', alt: 'NZXT F120 RGB core case fan', category: 'Upgrades & SSDs' }
];
