// File: src/constants/galleryPhotos.ts
//
// Real KCROC workshop photos added to /gallery (batch: seo-images, Oct 2026).
//
// Each photo ships as TWO WebP files in /public/images/gallery/:
//   <name>.w640.webp  - 640px thumbnail, used by the grid tiles (~40 KB)
//   <name>.webp       - 1400px full size, loaded only when a photo is opened
//                       in the lightbox (~150 KB)
// EXIF/GPS metadata was stripped during conversion.
//
// To add more photos: drop the two files into public/images/gallery/ and add
// one line below. Keep alt text specific (device + what is visible).

export type GalleryCategory =
  | 'Laptops'
  | 'Motherboards'
  | 'Gaming PCs'
  | 'Hardware Maintenance'
  | 'Workshop';

export interface GalleryPhoto {
  category: GalleryCategory;
  name: string;   // file stem in /images/gallery/
  alt: string;
  width: number;  // full-size pixel dimensions
  height: number;
  thumbWidth: number;
  thumbHeight: number;
}

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  { category: 'Gaming PCs', name: 'acer-predator-gaming-desktop-model-label-specifications-kuwait', alt: "Acer Predator gaming desktop model label specifications in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'acer-predator-gaming-pc-cooler-master-liquid-cooler-and-z37h4-aa-motherboard-kuwait', alt: "Acer Predator gaming PC Cooler Master liquid cooler and Z37H4-AA motherboard in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'acer-predator-orion-9000-gaming-pc-repair-kuwait', alt: "Acer Predator Orion 9000 gaming PC repair in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'acer-predator-z37h4-aa-lga-motherboard-replacement-kuwait', alt: "Acer Predator Z37H4-AA LGA motherboard replacement in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'acer-predator-z37h4-aa-motherboard-in-anti-static-bag-unboxing-kuwait', alt: "Acer Predator Z37H4-AA motherboard in anti-static bag unboxing in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'acer-predator-z37h4-aa-motherboard-with-amd-radeon-graphics-card-fan-kuwait', alt: "Acer Predator Z37H4-AA motherboard with AMD Radeon graphics card fan in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'alienware-laptop-internal-cleaning-fan-dust-battery-97wh-kuwait', alt: "Alienware laptop internal cleaning fan dust battery 97Wh in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'amd-ryzen-7-laptop-cpu-old-thermal-paste-before-repaste-kuwait', alt: "AMD Ryzen 7 laptop CPU old thermal paste before repaste in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'apple-imac-24-inch-m1-2021-blue-repair-service', alt: "Apple iMac 24 inch M1 2021 blue repair service", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'apple-magic-keyboard-arabic-magic-mouse-imac-m1', alt: "Apple magic keyboard arabic magic mouse iMac M1", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'arctic-mx-4-thermal-paste-application-laptop-cpu', alt: "Arctic MX 4 thermal paste application laptop CPU", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'arctic-mx-4-thermal-paste-on-intel-cpu-closeup', alt: "Arctic MX 4 thermal paste on Intel CPU closeup", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'argb-pwm-fan-controller-hub-9-port-pc-build-wiring-kuwait', alt: "ARGB PWM fan controller hub 9 port PC build wiring in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-gaming-laptop-heatsink-heat-pipes-dust-buildup-kuwait', alt: "ASUS gaming laptop heatsink heat pipes dust buildup in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'asus-prime-z590-p-bios-ez-mode-core-i7-10700k', alt: "ASUS prime Z590 p BIOS EZ mode Core I7 10700K", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-strix-g15-g513r-cooling-fan-dust-buildup-kuwait', alt: "ASUS ROG Strix G15 G513R cooling fan dust buildup in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-strix-g15-g513r-cpu-and-gpu-old-thermal-paste-before-repaste-kuwait', alt: "ASUS ROG Strix G15 G513R CPU and GPU old thermal paste before repaste in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-strix-g15-g513r-heatsink-old-thermal-paste-and-thermal-pads-kuwait', alt: "ASUS ROG Strix G15 G513R heatsink old thermal paste and thermal pads in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'asus-rog-strix-g15-g513r-motherboard-model-label-kuwait', alt: "ASUS ROG Strix G15 G513R motherboard model label in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-strix-g15-g513r-opened-dual-fan-cooling-system-ram-and-ssd-kuwait', alt: "ASUS ROG Strix G15 G513R opened dual fan cooling system RAM and SSD in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-strix-g15-g513r-second-cooling-fan-dusty-blades-kuwait', alt: "ASUS ROG Strix G15 G513R second cooling fan dusty blades in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'asus-rog-strix-z790-a-i9-14900k-64gb-ddr5-bios', alt: "ASUS ROG Strix Z790 a I9 14900K 64GB DDR5 BIOS", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-zephyrus-g16-gu605-cooling-fan-dust-on-blades-kuwait', alt: "ASUS ROG Zephyrus G16 GU605 cooling fan dust on blades in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-zephyrus-g16-gu605-heatsink-and-motherboard-dust-buildup-kuwait', alt: "ASUS ROG Zephyrus G16 GU605 heatsink and motherboard dust buildup in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'asus-rog-zephyrus-g16-gu605-oled-display-cable-and-hinge-bracket-kuwait', alt: "ASUS ROG Zephyrus G16 GU605 OLED display cable and hinge bracket in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'asus-rog-zephyrus-g16-gu605-opened-90wh-battery-triple-fan-cooling-kuwait', alt: "ASUS ROG Zephyrus G16 GU605 opened 90Wh battery triple fan cooling in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'clogged-laptop-heatsink-fins-dust-removal', alt: "Clogged laptop heatsink fins dust removal", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Workshop', name: 'computer-repair-shop-kuwait-graphics-cards-rtx-5060-technician', alt: "Computer repair shop graphics cards RTX 5060 technician in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'dell-desktop-pc-repair-open-case-booting', alt: "Dell desktop PC repair open case booting", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-gaming-laptop-back-cover-removed-97wh-battery-kuwait', alt: "Dell gaming laptop back cover removed 97Wh battery in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-gaming-laptop-dust-buildup-on-fan-blades-kuwait', alt: "Dell gaming laptop dust buildup on fan blades in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-gaming-laptop-dusty-cooling-fan-before-cleaning-kuwait', alt: "Dell gaming laptop dusty cooling fan before cleaning in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'dell-gaming-laptop-motherboard-removed-with-dual-fan-heatsink-kuwait', alt: "Dell gaming laptop motherboard removed with dual fan heatsink in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-gaming-laptop-nvidia-gpu-amd-ryzen-7-cleaned-ready-for-new-thermal-paste-kuwait', alt: "Dell gaming laptop NVIDIA GPU AMD Ryzen 7 cleaned ready for new thermal paste in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-grnx5-battery-label-14-8v-80wh-0v9tyf', alt: "Dell GRNX5 battery label 14 8V 80Wh 0V9TYF", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-grnx5-laptop-battery-replacement-kuwait', alt: "Dell GRNX5 laptop battery replacement in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-inspiron-n4030-laptop-ram-slot-and-ssd-upgrade-kuwait', alt: "Dell Inspiron N4030 laptop RAM slot and SSD upgrade in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-laptop-cooling-fan-dust-buildup-on-blades-kuwait', alt: "Dell laptop cooling fan dust buildup on blades in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-laptop-cpu-cooling-fan-dust-buildup-cleaning', alt: "Dell laptop CPU cooling fan with dust buildup needing cleaning", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-laptop-hdd-replaced-with-crucial-bx500-240gb-ssd-upgrade-kuwait', alt: "Dell laptop HDD replaced with Crucial BX500 240GB SSD upgrade in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-laptop-heatsink-old-dried-thermal-paste-cpu-and-gpu-contact-plates-kuwait', alt: "Dell laptop heatsink old dried thermal paste CPU and GPU contact plates in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'dell-laptop-motherboard-cpu-fan-heatsink-ram-slot-closeup', alt: "Close-up of Dell laptop motherboard with CPU fan, heatsink and RAM slot", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dell-laptop-opened-dusty-fan-and-old-thermal-paste-on-cpu-kuwait', alt: "Dell laptop opened dusty fan and old thermal paste on CPU in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-laptop-windows-11-running-after-repair-old-hard-drive-removed-kuwait', alt: "Dell laptop Windows 11 running after repair old hard drive removed in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-laptop-windows-11-working-after-repair-kuwait', alt: "Dell laptop Windows 11 working after repair in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-vostro-3350-laptop-repair-service-kuwait', alt: "Dell Vostro 3350 laptop repair service in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-vostro-laptop-bottom-base-cover-disassembly', alt: "Dell Vostro laptop base cover during disassembly", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'dell-vostro-laptop-motherboard-removed-fan-heatsink-chip-level-repair', alt: "Dell Vostro laptop motherboard removed with fan and heatsink on repair bench", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'dell-vostro-laptop-motherboard-repair-disassembled', alt: "Dell Vostro laptop motherboard repair disassembled", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-vostro-laptop-old-cmos-battery-removal', alt: "Dell Vostro laptop old CMOS battery removal", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'dell-vostro-laptop-open-chassis-motherboard-removed', alt: "Dell Vostro laptop chassis opened with motherboard removed", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-vostro-palmrest-top-cover-replacement', alt: "Dell Vostro palmrest top cover with touchpad area", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'dell-vostro-palmrest-touchpad-synaptics-underside', alt: "Dell Vostro palmrest underside showing Synaptics touchpad", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dust-and-lint-removed-from-laptop-cooling-system-kuwait', alt: "Dust and lint removed from laptop cooling system in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'dusty-laptop-cooling-fan-cleaning-overheating-fix', alt: "Dusty laptop cooling fan cleaning overheating fix", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'gaming-laptop-cooling-fan-housing-thermal-pad-inspection', alt: "Gaming laptop cooling fan housing thermal pad inspection", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'gaming-laptop-exhaust-vent-dust-buildup-cleaning', alt: "Gaming laptop exhaust vent dust buildup cleaning", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'gaming-laptop-motherboard-fan-area-thermal-pads-dust-cleaning', alt: "Gaming laptop motherboard fan area thermal pads dust cleaning", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'gigabyte-b760-ds3h-ax-bios-core-i7-14700f-pc-build-kuwait', alt: "Gigabyte B760 DS3H ax BIOS Core I7 14700F PC build in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'gigabyte-gaming-laptop-internals-dual-fan-cooling-ssd-ram-upgrade-kuwait', alt: "Gigabyte gaming laptop internals dual fan cooling SSD RAM upgrade in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'gigabyte-laptop-motherboard-pch-chip-dried-thermal-paste-ram-slots-kuwait', alt: "Gigabyte laptop motherboard PCH chip dried thermal paste RAM slots in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'graphics-card-disassembled-heatsink-gpu-old-thermal-paste-and-dusty-fans-kuwait', alt: "Graphics card disassembled heatsink GPU old thermal paste and dusty fans in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'graphics-card-gpu-die-old-thermal-paste-and-green-thermal-pads-kuwait', alt: "Graphics card GPU die old thermal paste and green thermal pads in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-all-in-one-24-cb1xxx-bios-setup-core-i5-1235u', alt: "HP All-in-One 24-cb1xxx BIOS setup screen showing Core i5-1235U and 8GB RAM", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-all-in-one-24-motherboard-fan-heatsink-ram-inside-view', alt: "Inside view of HP All-in-One 24 motherboard, cooling fan, heatsink and RAM", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-all-in-one-bios-no-disks-connected-intel-rst-vmd-error', alt: "HP All-in-One BIOS showing No disks connected to system in Intel RST VMD", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-all-in-one-pc-lcd-screen-panel-removal-repair', alt: "HP All-in-One PC LCD panel removed for internal repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'hp-desktop-pc-cpu-cooler-fan-and-ram-slots-inside-view-kuwait', alt: "HP desktop PC CPU cooler fan and RAM slots inside view in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'hp-desktop-pc-opened-motherboard-psu-ssd-and-hard-drive-kuwait', alt: "HP desktop PC opened motherboard PSU SSD and hard drive in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'hp-desktop-pc-sata-cables-wd-green-240gb-ssd-and-hard-drive-kuwait', alt: "HP desktop PC SATA cables WD green 240GB SSD and hard drive in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-laptop-cooling-fan-l52034-001-inspection', alt: "HP laptop cooling fan L52034 001 inspection", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-laptop-internal-cleaning-service-battery-removed', alt: "HP laptop internal cleaning service battery removed", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'hp-laptop-motherboard-heatsink-m2-ssd-closeup', alt: "HP laptop motherboard heatsink M.2 SSD closeup", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-omen-gaming-laptop-internal-view-dual-fans-heatsink', alt: "HP OMEN gaming laptop internal view dual fans heatsink", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'hp-stream-13-blue-laptop-front-view-repair', alt: "HP Stream 13 blue laptop front view repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'hp-stream-13-blue-laptop-windows-10-working-after-repair', alt: "HP Stream 13 blue laptop Windows 10 working after repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'hp-stream-blue-laptop-keyboard-touchpad-closeup', alt: "HP Stream blue laptop keyboard touchpad closeup", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'hp-stream-blue-laptop-top-view-diagnostics', alt: "HP Stream blue laptop top view diagnostics", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'hp-stream-celeron-n3050-2gb-ram-windows-10-system-info', alt: "HP Stream Celeron N3050 2GB RAM Windows 10 system info", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'hp-v214a-led-monitor-repair-kuwait', alt: "HP V214A LED monitor repair in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-blower-fan-cleaned-and-heatsink-removed-kuwait', alt: "Laptop blower fan cleaned and heatsink removed in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cooling-fan-12v-label-dust-on-blades-kuwait', alt: "Laptop cooling fan 12V label dust on blades in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cooling-fan-heatsink-assembly-cleaning-repair', alt: "Laptop cooling fan and heatsink assembly opened for cleaning and repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cooling-system-dust-buildup-underside-kuwait', alt: "Laptop cooling system dust buildup underside in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-copper-heatsink-old-thermal-paste-cleaning', alt: "Laptop copper heatsink with old thermal paste ready for cleaning", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cpu-dried-thermal-paste-needs-repaste', alt: "Laptop CPU with old dried thermal paste before repasting", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cpu-gpu-new-thermal-paste-applied-repaste-service', alt: "Laptop CPU GPU new thermal paste applied repaste service", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cpu-old-dried-thermal-paste-before-cleaning', alt: "Laptop CPU old dried thermal paste before cleaning", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cpu-repaste-service-fresh-thermal-compound', alt: "Laptop CPU repaste service fresh thermal compound", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cpu-thermal-paste-reapplication-intel-core', alt: "Laptop CPU thermal paste reapplication Intel Core", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-cpu-thermal-paste-replacement-service-kuwait', alt: "Laptop CPU thermal paste replacement service in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-dual-fan-cooling-system-dusty-fan-blades-kuwait', alt: "Laptop dual fan cooling system dusty fan blades in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-fan-and-heatsink-deep-cleaning-kuwait', alt: "Laptop fan and heatsink deep cleaning in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-gpu-chip-old-dried-thermal-paste-before-repaste-kuwait', alt: "Laptop GPU chip old dried thermal paste before repaste in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-gpu-old-dried-thermal-paste-before-repaste-kuwait', alt: "Laptop GPU old dried thermal paste before repaste in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-gpu-old-dried-thermal-paste-replacement-kuwait', alt: "Laptop GPU old dried thermal paste replacement in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-copper-contact-dried-thermal-paste', alt: "Laptop heatsink copper contact dried thermal paste", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-copper-plates-old-thermal-paste-and-pads-kuwait', alt: "Laptop heatsink copper plates old thermal paste and pads in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-deep-cleaning-lint-removal-kuwait', alt: "Laptop heatsink deep cleaning lint removal in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-dried-thermal-paste-and-worn-thermal-pads-kuwait', alt: "Laptop heatsink dried thermal paste and worn thermal pads in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-exhaust-fins-blocked-by-lint-and-hair-kuwait', alt: "Laptop heatsink exhaust fins blocked by lint and hair in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-fan-clogged-with-dust-needs-cleaning-kuwait', alt: "Laptop heatsink fan clogged with dust needs cleaning in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-heatsink-fins-clogged-with-dust-overheating-kuwait', alt: "Laptop heatsink fins clogged with dust overheating in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-intel-cpu-nvidia-gpu-cleaned-before-repaste', alt: "Laptop Intel CPU NVIDIA GPU cleaned before repaste", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-internal-cleaning-dust-removal-service-kuwait', alt: "Laptop internal cleaning dust removal service in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-motherboard-and-dual-fan-heatsink-disassembled-for-cleaning-kuwait', alt: "Laptop motherboard and dual fan heatsink disassembled for cleaning in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-motherboard-intel-cpu-old-dried-thermal-paste-before-repaste-kuwait', alt: "Laptop motherboard Intel CPU old dried thermal paste before repaste in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-overheating-repair-dusty-heatsink-fins-kuwait', alt: "Laptop overheating repair dusty heatsink fins in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'laptop-processor-cracked-thermal-paste-overheating-repair', alt: "Laptop processor cracked thermal paste overheating repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'lenovo-ideapad-5-pro-14-ryzen-7-5000-laptop-repair', alt: "Lenovo IdeaPad 5 Pro 14 Ryzen 7 5000 laptop repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'lenovo-ideapad-5-pro-14acn6-model-label-82l7', alt: "Lenovo IdeaPad 5 Pro 14ACN6 model label 82L7", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-laptop-bottom-cover-removed-cpu-fan-and-battery-kuwait', alt: "Lenovo laptop bottom cover removed CPU fan and battery in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-laptop-cooling-fan-removed-for-replacement-kuwait', alt: "Lenovo laptop cooling fan removed for replacement in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-laptop-cooling-fan-side-view-air-vent-fins-kuwait', alt: "Lenovo laptop cooling fan side view air vent fins in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-laptop-old-cooling-fan-removed-next-to-new-fan-installation-kuwait', alt: "Lenovo laptop old cooling fan removed next to new fan installation in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-laptop-opened-cooling-fan-and-heatsink-removed-for-cleaning-kuwait', alt: "Lenovo laptop opened cooling fan and heatsink removed for cleaning in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-laptop-replacement-cooling-fan-part-number-label-kuwait', alt: "Lenovo laptop replacement cooling fan part number label in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'lenovo-legion-7-16ithg6-bottom-cover-inside-label-kuwait', alt: "Lenovo Legion 7 16ITHG6 bottom cover inside label in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'lenovo-legion-7-16ithg6-model-label-and-air-vents-kuwait', alt: "Lenovo Legion 7 16ITHG6 model label and air vents in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-legion-7-16ithg6-opened-dual-fan-cooling-system-and-battery-kuwait', alt: "Lenovo Legion 7 16ITHG6 opened dual fan cooling system and battery in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-legion-laptop-clean-cooling-fan-after-cleaning', alt: "Lenovo Legion laptop clean cooling fan after cleaning", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-legion-laptop-heatsink-dust-blocking-fan-airflow', alt: "Lenovo Legion laptop heatsink dust blocking fan airflow", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-legion-laptop-heatsink-removed-thermal-pads-old-paste', alt: "Lenovo Legion laptop heatsink removed thermal pads old paste", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-legion-laptop-left-fan-dust-buildup', alt: "Lenovo Legion laptop left fan dust buildup", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-legion-laptop-right-fan-dust-buildup', alt: "Lenovo Legion laptop right fan dust buildup", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'lenovo-v30a-22iml-all-in-one-pc-model-label', alt: "Lenovo V30A 22IML all in one PC model label", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'macbook-air-13-inch-repair-ssd-upgrade-kuwait', alt: "MacBook Air 13 inch repair SSD upgrade in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'macbook-air-sandisk-256gb-ssd-replacement-kuwait', alt: "MacBook Air SanDisk 256GB SSD replacement in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'macbook-logic-board-cleaning-crc-contact-cleaner', alt: "MacBook logic board cleaning CRC contact cleaner", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'macbook-pro-16-inch-2021-internal-fans-battery-a2527', alt: "MacBook Pro 16 inch 2021 internal fans battery A2527", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'macbook-pro-16-inch-logic-board-heatsink-thermal-pads', alt: "MacBook Pro 16 inch logic board heatsink thermal pads", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'macbook-pro-16-m1-logic-board-motherboard-repair', alt: "MacBook Pro 16 M1 logic board motherboard repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'macbook-pro-logic-board-power-section-usb-c-controller-chips', alt: "MacBook Pro logic board power section USB-C controller chips", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'macbook-pro-m1-chip-logic-board-top-view', alt: "MacBook Pro M1 chip logic board top view", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'macbook-pro-retina-13-inch-a1502-inside-battery-removed', alt: "MacBook Pro Retina 13 inch A1502 inside battery removed", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'macbook-pro-retina-13-inch-opened-on-repair-bench', alt: "MacBook Pro Retina 13 inch opened on repair bench", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'macbook-pro-retina-13-inch-swollen-battery-replacement', alt: "MacBook Pro Retina 13 inch swollen battery replacement", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Motherboards', name: 'macbook-pro-thunderbolt-usb-c-port-replacement-board-repair', alt: "MacBook Pro Thunderbolt USB-C port replacement board repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'msi-laptop-secure-boot-violation-invalid-signature-fix-kuwait', alt: "MSI laptop secure boot violation invalid signature fix in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'old-dried-thermal-paste-laptop-heatsink-replacement', alt: "Old dried thermal paste laptop heatsink replacement", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'panasonic-cr2032-3v-lithium-cmos-battery-pack', alt: "Panasonic CR2032 3V lithium CMOS battery pack", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'panasonic-cr2032-cmos-battery-replacement-laptop-motherboard', alt: "Panasonic CR2032 CMOS battery replacement laptop motherboard", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'pc-argb-fan-hub-cable-management-white-gaming-pc-build-kuwait', alt: "PC ARGB fan hub cable management white gaming PC build in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Workshop', name: 'pc-parts-shop-kuwait-liquid-coolers-power-supplies-motherboards', alt: "PC parts shop liquid coolers power supplies motherboards in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-dust-from-laptop-heatsink-with-tweezers-kuwait', alt: "Removing dust from laptop heatsink with tweezers in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-dust-from-laptop-heatsink-with-tweezers-step-1-kuwait', alt: "Removing dust from laptop heatsink with tweezers step 1 in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-dust-from-laptop-heatsink-with-tweezers-step-2-kuwait', alt: "Removing dust from laptop heatsink with tweezers step 2 in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-dust-from-laptop-heatsink-with-tweezers-step-3-kuwait', alt: "Removing dust from laptop heatsink with tweezers step 3 in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-dust-from-laptop-heatsink-with-tweezers', alt: "Removing dust from laptop heatsink with tweezers", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-dust-lint-gaming-laptop-heatsink-tweezers', alt: "Removing dust lint gaming laptop heatsink tweezers", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'removing-lint-from-laptop-heatsink-fins-with-tweezers-kuwait', alt: "Removing lint from laptop heatsink fins with tweezers in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'samsung-16gb-ddr4-3200-laptop-ram-sodimm-upgrade-kuwait', alt: "Samsung 16GB DDR4 3200 laptop RAM SODIMM upgrade in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'samsung-pm991a-512gb-nvme-m2-ssd-hp-all-in-one', alt: "Samsung PM991a 512GB NVMe M.2 SSD removed from HP All-in-One", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'thermaltake-ddr4-3600-16gb-ram-kit-2x8gb-kuwait', alt: "Thermaltake DDR4 3600 16GB RAM kit 2X8GB in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'toshiba-laptop-broken-top-cover-hinge-corner-replacement', alt: "Broken top cover and hinge corner of Toshiba laptop before replacement", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'toshiba-satellite-laptop-cracked-lid-corner-damage-repair', alt: "Toshiba laptop with cracked lid corner needing casing repair", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Laptops', name: 'toshiba-satellite-pro-l40-laptop-model-label', alt: "Toshiba Satellite Pro L40 laptop model label", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Hardware Maintenance', name: 'wd-sn740-512gb-nvme-m2-ssd-installed-hp-all-in-one', alt: "WD SN740 512GB NVMe M.2 SSD installed in HP All-in-One next to WiFi card", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'zotac-gaming-geforce-rtx-graphics-card-side-view-kuwait', alt: "ZOTAC gaming GeForce RTX graphics card side view in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'zotac-gaming-geforce-rtx-triple-fan-graphics-card-repair-kuwait', alt: "ZOTAC gaming GeForce RTX triple fan graphics card repair in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
  { category: 'Gaming PCs', name: 'zotac-geforce-rtx-graphics-card-backplate-old-thermal-pads-kuwait', alt: "ZOTAC GeForce RTX graphics card backplate old thermal pads in Kuwait", width: 1400, height: 1400, thumbWidth: 640, thumbHeight: 640 },
];
