// File: src/constants/images.ts

export const IMAGES = {
  // --- BRANDING & SHOP ---
  brand: {
    shopExteriorDusk: { src: "/images/kcroc-commercial-complex-view-dusk.webp", alt: "KCROC shop exterior at dusk", width: 1200, height: 800 },
    shopExteriorDay: { src: "/images/kcroc-al-mullah-complex-hawalli-exterior.webp", alt: "KCROC shop front daytime", width: 1200, height: 800 },
    shopExteriorNight: { src: "/images/kcroc-al-mullah-complex-hawalli-night-view.webp", alt: "KCROC shop night view", width: 1200, height: 800 },
    shopEntrance: { src: "/images/kcroc-al-mullah-complex-basement-shop-entrance.webp", alt: "KCROC shop entrance", width: 800, height: 600 },
    shopInterior: { src: "/images/computer-repair-shop-hawalli-kuwait.webp", alt: "Interior of KCROC shop", width: 1200, height: 800 },
    inventory: { src: "/images/kcroc-laptop-repair-parts-inventory-shelves.webp", alt: "Spare parts inventory", width: 1000, height: 800 },
    team: { src: "/images/kcroc-computer-repair-technician-team.webp", alt: "KCROC technical team", width: 1200, height: 630 },
    owner: { src: "/images/kcroc-imran-natiq-laptop-repair-workshop-owner.webp", alt: "Workshop owner Imran Natiq", width: 800, height: 800 },
    cofounder: { src: "/images/kcroc-team-member-imran-hat-fun.webp", alt: "KCROC Team Member", width: 400, height: 400 },
    technicians: { src: "/images/kcroc-laptop-repair-technicians-hawalli-kuwait.webp", alt: "Technicians at work", width: 1200, height: 800 },
    leadTechnician: { src: "/images/kcroc-lead-technician-laptop-repair-workbench.webp", alt: "Lead technician working", width: 1200, height: 800 },
    pcDoctor: { src: "/images/kcroc-pc-doctor-windows-repair-services.webp", alt: "PC Doctor services", width: 800, height: 600 },
    teamFun: { src: "/images/kcroc-team-member-imran-hat-fun.webp", alt: "KCROC team fun", width: 800, height: 800 },
    logo: { src: "/logo.webp", alt: "KCROC Logo", width: 224, height: 224 },
    // ✅ Updated to the verified lead technician workbench image
    heroBanner: { 
      src: "/images/kcroc-lead-technician-laptop-repair-workbench.webp", 
      alt: "Professional technician working on a laptop at the KCROC workshop in Hawalli", 
      width: 1200, 
      height: 600 
    },
    kcrocComputerPartsShopInteriorShelves: { src: "/images/kcroc-computer-parts-shop-interior-shelves.webp", alt: "KCROC Computer Parts Shop Interior Shelves", width: 800, height: 600 },
    kcrocKuwaitComputerRepairLogo: { src: "/images/kcroc-kuwait-computer-repair-logo.webp", alt: "KCROC Kuwait Computer Repair Logo", width: 800, height: 600 },
    kcrocShopPcCaseRetailDisplay: { src: "/images/kcroc-shop-pc-case-retail-display.webp", alt: "KCROC Shop PC Case Retail Display", width: 800, height: 600 },
    kcrocShopPcCasesRetailShelf: { src: "/images/kcroc-shop-pc-cases-retail-shelf.webp", alt: "KCROC Shop PC Cases Retail Shelf", width: 800, height: 600 },
    laptopRepairShopWorkbenchLaptops: { src: "/images/laptop-repair-shop-workbench-laptops.webp", alt: "Laptop Repair Shop Workbench Laptops", width: 800, height: 600 },
    pcCaseFrontUsbPortsShopDesk: { src: "/images/pc-case-front-usb-ports-shop-desk.webp", alt: "PC Case Front USB Ports Shop Desk", width: 800, height: 600 },
  },

  // --- GENERAL SERVICES ---
  services: {
    laptopRepair: { src: "/images/laptop-repair-kuwait.webp", alt: "Professional laptop repair in Kuwait", width: 1200, height: 630 },
    motherboardRepair: { src: "/images/motherboard-repair-kuwait.webp", alt: "Advanced chip-level motherboard repair", width: 1200, height: 630 },
    windowsInstall: { src: "/images/windows-os-software-repair-and-installation-kuwait.webp", alt: "Windows OS installation service", width: 1000, height: 600 },
    windows11Gaming: { src: "/images/windows-11-operating-system-installation-gaming-pc.webp", alt: "Windows 11 OS installation gaming PC", width: 1000, height: 600 },
    dellWindows: { src: "/images/dell-laptop-windows-operating-system-installation.webp", alt: "Dell laptop Windows OS installation", width: 1000, height: 600 },
    thermalService: { src: "/images/laptop-thermal-paste-application-service.webp", alt: "Thermal paste application service", width: 800, height: 600 }
  },

  // --- MACBOOK REPAIR ---
  macbook: {
    logicBoard: { src: "/images/apple-macbook-logic-board-and-fan-repair.webp", alt: "MacBook logic board repair", width: 1000, height: 600 },
    diagnostics: { src: "/images/technician-holding-opened-macbook-for-repair.webp", alt: "MacBook diagnostics", width: 1200, height: 630 },
    swollenBattery1: { src: "/images/swollen-apple-macbook-battery-replacement.webp", alt: "Swollen MacBook battery", width: 800, height: 600 },
    swollenBattery2: { src: "/images/swollen-macbook-battery-replacement-2.webp", alt: "MacBook battery replacement", width: 800, height: 600 },
    swollenBattery3: { src: "/images/swollen-macbook-internal-battery-replacement.webp", alt: "Internal battery replacement", width: 800, height: 600 },
    expandedBattery: { src: "/images/expanded-macbook-pro-battery-removal.webp", alt: "Expanded MacBook Pro battery removal", width: 800, height: 600 },
    hardwareRepair: { src: "/images/macbook-internal-battery-hardware-repair.webp", alt: "MacBook hardware repair", width: 800, height: 600 },
    service: { src: "/images/macbook-internal-battery-replacement-service.webp", alt: "MacBook battery service", width: 800, height: 600 },
    macbookProBatteryRamInstalled: { src: "/images/macbook-pro-battery-ram-installed.webp", alt: "MacBook Pro Battery RAM Installed", width: 800, height: 600 },
    macbookProBatteryRemovalRepair: { src: "/images/macbook-pro-battery-removal-repair.webp", alt: "MacBook Pro Battery Removal Repair", width: 800, height: 600 },
    macbookProOpenMacosScreen: { src: "/images/macbook-pro-open-macos-screen.webp", alt: "MacBook Pro Open Macos Screen", width: 800, height: 600 },
    macbookUnboxingRepairWorkshop: { src: "/images/macbook-unboxing-repair-workshop.webp", alt: "MacBook Unboxing Repair Workshop", width: 800, height: 600 },
  },

  // --- GAMING & CUSTOM PCs ---
  gaming: {
    rgbLighting: { src: "/images/custom-gaming-pc-build-rgb-lighting-kuwait.webp", alt: "Custom Gaming PC RGB Lighting", width: 1200, height: 800 },
    waterCooled: { src: "/images/custom-water-cooled-gaming-pc-build-kuwait.webp", alt: "Water cooled gaming PC build", width: 1200, height: 800 },
    msiGpuBuild: { src: "/images/custom-gaming-pc-msi-gpu-intel-cooler-build.webp", alt: "MSI GPU Intel Cooler Build", width: 1200, height: 800 },
    darkflashCooler: { src: "/images/custom-desktop-pc-msi-gpu-darkflash-cooler.webp", alt: "Darkflash Cooler Build", width: 1200, height: 800 },
    asusRogCase: { src: "/images/asus-rog-gaming-pc-rgb-case-build.webp", alt: "ASUS ROG RGB Case Build", width: 1200, height: 800 },
    rtxLighting: { src: "/images/geforce-rtx-gaming-pc-rgb-lighting.webp", alt: "GeForce RTX Gaming PC", width: 1200, height: 800 },
    deepcoolAio: { src: "/images/gaming-pc-deepcool-aio-liquid-cooler-installation.webp", alt: "Deepcool AIO Liquid Cooler", width: 1200, height: 800 },
    sleevedCables: { src: "/images/asus-rog-custom-pc-sleeved-cables.webp", alt: "Custom PC Sleeved Cables", width: 800, height: 600 },
    gpuUpgrade: { src: "/images/zotac-gaming-graphics-card-gpu-upgrade.webp", alt: "Zotac Gaming GPU Upgrade", width: 800, height: 600 },
    zotacCard: { src: "/images/technician-holding-zotac-gaming-graphics-card.webp", alt: "Zotac Gaming Graphics Card", width: 800, height: 600 },
    diagnostics: { src: "/images/custom-gaming-pc-teardown-and-diagnostics-workbench.webp", alt: "Gaming PC Diagnostics", width: 1200, height: 630 },
    ttCooler: { src: "/images/custom-pc-build-msi-motherboard-thermaltake-cooler.webp", alt: "MSI Motherboard Thermaltake Cooler", width: 1200, height: 800 },
    asusRogFan: { src: "/images/asus-rog-motherboard-vrm-cooling-fan.webp", alt: "ASUS ROG VRM Cooling Fan", width: 800, height: 600 },
    asusRogPaste: { src: "/images/asus-rog-z790-motherboard-cpu-thermal-paste.webp", alt: "ASUS ROG Z790 CPU Thermal Paste", width: 800, height: 600 },
    msiWorkstation: { src: "/images/msi-gaming-laptop-and-gpu-repair-workstation.webp", alt: "MSI Gaming Laptop Repair Workstation", width: 1200, height: 800 },
    nzxtFan: { src: "/images/nzxt-f120-rgb-core-case-fan.webp", alt: "NZXT F120 RGB Core Case Fan", width: 800, height: 600 },
    gamingLaptopFan: { src: "/images/gaming-laptop-dual-fan-motherboard-diagnostics.webp", alt: "Gaming Laptop Dual Fan Diagnostics", width: 800, height: 600 },
    gamingOverheating: { src: "/images/gaming-laptop-overheating-repair.webp", alt: "Gaming Laptop Overheating Repair", width: 800, height: 600 },
    asusRogCpuThermalPasteGpuBuild: { src: "/images/asus-rog-cpu-thermal-paste-gpu-build.webp", alt: "ASUS ROG CPU Thermal Paste GPU Build", width: 800, height: 600 },
    asusRogGamingPcFanRadiatorBuild: { src: "/images/asus-rog-gaming-pc-fan-radiator-build.webp", alt: "ASUS ROG Gaming PC Fan Radiator Build", width: 800, height: 600 },
    asusRogStrixCpuThermalPasteInstalled: { src: "/images/asus-rog-strix-cpu-thermal-paste-installed.webp", alt: "ASUS ROG Strix CPU Thermal Paste Installed", width: 800, height: 600 },
    asusRogWhitePcCaseBuild: { src: "/images/asus-rog-white-pc-case-build.webp", alt: "ASUS ROG White PC Case Build", width: 800, height: 600 },
    customGamingPcCaseBuildInterior: { src: "/images/custom-gaming-pc-case-build-interior.webp", alt: "Custom Gaming PC Case Build Interior", width: 800, height: 600 },
    customPcAioLiquidCoolerInstallation: { src: "/images/custom-pc-aio-liquid-cooler-installation.webp", alt: "Custom PC AIO Liquid Cooler Installation", width: 800, height: 600 },
    customPcBuildMotherboardCablesInterior: { src: "/images/custom-pc-build-motherboard-cables-interior.webp", alt: "Custom PC Build Motherboard Cables Interior", width: 800, height: 600 },
    customPcWhiteAioCoolerBuild: { src: "/images/custom-pc-white-aio-cooler-build.webp", alt: "Custom PC White AIO Cooler Build", width: 800, height: 600 },
    customPcWhiteCableManagementBuild: { src: "/images/custom-pc-white-cable-management-build.webp", alt: "Custom PC White Cable Management Build", width: 800, height: 600 },
    evgaPcCaseDualFanInterior: { src: "/images/evga-pc-case-dual-fan-interior.webp", alt: "EVGA PC Case Dual Fan Interior", width: 800, height: 600 },
    gamingLaptopPowerAdapterCharger: { src: "/images/gaming-laptop-power-adapter-charger.webp", alt: "Gaming Laptop Power Adapter Charger", width: 800, height: 600 },
    gamingMotherboardCpuSocketPcieSlots: { src: "/images/gaming-motherboard-cpu-socket-pcie-slots.webp", alt: "Gaming Motherboard CPU Socket PCIe Slots", width: 800, height: 600 },
    gamingMotherboardHeatsinkUnboxing: { src: "/images/gaming-motherboard-heatsink-unboxing.webp", alt: "Gaming Motherboard Heatsink Unboxing", width: 800, height: 600 },
    gamingMotherboardRamInstalledCloseup: { src: "/images/gaming-motherboard-ram-installed-closeup.webp", alt: "Gaming Motherboard RAM Installed Closeup", width: 800, height: 600 },
    gamingPcRgbInstallingWindows11: { src: "/images/gaming-pc-rgb-installing-windows-11.webp", alt: "Gaming PC RGB Installing Windows 11", width: 800, height: 600 },
    gamingPcThermalThrottlingKuwait: { src: "/images/gaming-pc-thermal-throttling-kuwait.webp", alt: "Gaming PC Thermal Throttling Kuwait", width: 800, height: 600 },
    geforceRtxGpuGamingPcRgbFans: { src: "/images/geforce-rtx-gpu-gaming-pc-rgb-fans.webp", alt: "Geforce RTX GPU Gaming PC RGB Fans", width: 800, height: 600 },
    msiH170GamingMotherboardCpuCooler: { src: "/images/msi-h170-gaming-motherboard-cpu-cooler.webp", alt: "MSI H170 Gaming Motherboard CPU Cooler", width: 800, height: 600 },
    pcCaseDualFanGpuInterior: { src: "/images/pc-case-dual-fan-gpu-interior.webp", alt: "PC Case Dual Fan GPU Interior", width: 800, height: 600 },
    pcCaseTemperedGlassRetailDisplay: { src: "/images/pc-case-tempered-glass-retail-display.webp", alt: "PC Case Tempered Glass Retail Display", width: 800, height: 600 },
    rgbGamingPcBuildInterior: { src: "/images/rgb-gaming-pc-build-interior.webp", alt: "RGB Gaming PC Build Interior", width: 800, height: 600 },
    rgbGamingPcRadiatorBuildInterior: { src: "/images/rgb-gaming-pc-radiator-build-interior.webp", alt: "RGB Gaming PC Radiator Build Interior", width: 800, height: 600 },
  },

  // --- UPGRADES: SSD & RAM ---
  upgrades: {
    ram8gb: { src: "/images/8gb-ddr4-ram-memory-upgrade.webp", alt: "8GB DDR4 RAM Upgrade", width: 800, height: 600 },
    ramHynix1: { src: "/images/installing-sk-hynix-8gb-ddr4-ram.webp", alt: "Installing SK Hynix 8GB DDR4 RAM", width: 800, height: 600 },
    ramHynix2: { src: "/images/sk-hynix-8gb-ddr4-laptop-ram-memory.webp", alt: "SK Hynix 8GB DDR4 Laptop RAM", width: 800, height: 600 },
    ramHynix3: { src: "/images/sk-hynix-pc3l-laptop-ram-memory-upgrade.webp", alt: "SK Hynix PC3L RAM Upgrade", width: 800, height: 600 },
    cpuI7: { src: "/images/intel-core-i7-14th-gen-cpu-upgrade.webp", alt: "Intel Core i7 14th Gen CPU Upgrade", width: 800, height: 600 },
    ssdCorsair: { src: "/images/corsair-mp600-core-xt-nvme-ssd-upgrade.webp", alt: "Corsair MP600 NVMe SSD Upgrade", width: 800, height: 600 },
    ssdKioxia: { src: "/images/kioxia-128gb-m2-ssd-laptop-storage-upgrade.webp", alt: "Kioxia 128GB M.2 SSD Upgrade", width: 800, height: 600 },
    ssdLexar1: { src: "/images/lexar-256gb-sata-ssd-laptop-upgrade.webp", alt: "Lexar 256GB SATA SSD Upgrade", width: 800, height: 600 },
    ssdLexar2: { src: "/images/lexar-nm620-m2-nvme-ssd-installation.webp", alt: "Lexar NM620 M.2 SSD Installation", width: 800, height: 600 },
    ssdLexar3: { src: "/images/lexar-ssd-installation-laptop-internals.webp", alt: "Lexar SSD Installation", width: 800, height: 600 },
    ssdSamsung1: { src: "/images/samsung-960-evo-nvme-m2-ssd-250gb.webp", alt: "Samsung 960 EVO NVMe M.2 SSD", width: 800, height: 600 },
    ssdSamsung2: { src: "/images/samsung-ssd-laptop-upgrade-kuwait.webp", alt: "Samsung SSD Laptop Upgrade", width: 800, height: 600 },
    ssdWDBlack: { src: "/images/wd-black-sn850-1tb-nvme-ssd-upgrade.webp", alt: "WD Black SN850 1TB NVMe SSD", width: 800, height: 600 },
    ssdWDBlue: { src: "/images/wd-blue-2tb-nvme-ssd-upgrade-part.webp", alt: "WD Blue 2TB NVMe SSD", width: 800, height: 600 },
    ssdMicron: { src: "/images/micron-m2-nvme-ssd-laptop-storage.webp", alt: "Micron M.2 NVMe SSD", width: 800, height: 600 },
    ssdM2Install: { src: "/images/m2-nvme-ssd-motherboard-installation.webp", alt: "M.2 NVMe SSD Installation", width: 800, height: 600 },
    ssdNewPart: { src: "/images/new-m2-nvme-ssd-replacement-part.webp", alt: "New M.2 NVMe SSD Part", width: 800, height: 600 },
    hddSeagate: { src: "/images/seagate-1tb-mobile-hdd-laptop-hard-drive.webp", alt: "Seagate 1TB Mobile HDD", width: 800, height: 600 },
    hddCaddy: { src: "/images/laptop-sata-2nd-hdd-caddy-9-5mm.webp", alt: "Laptop SATA 2nd HDD Caddy", width: 800, height: 600 },
    miniPcCrucial: { src: "/images/mini-pc-crucial-ddr5-ram-and-nvme-ssd-upgrade.webp", alt: "Mini PC Crucial DDR5 RAM & SSD Upgrade", width: 800, height: 600 },
    acerLaptopMotherboardRamHeatsink: { src: "/images/acer-laptop-motherboard-ram-heatsink.webp", alt: "Acer Laptop Motherboard RAM Heatsink", width: 800, height: 600 },
    corsairMp600CoreXtNvmeSsdInstallation: { src: "/images/corsair-mp600-core-xt-nvme-ssd-installation.webp", alt: "Corsair Mp600 Core Xt NVMe SSD Installation", width: 800, height: 600 },
    ddr3lRamStickLaptopUpgrade: { src: "/images/ddr3l-ram-stick-laptop-upgrade.webp", alt: "DDR3L RAM Stick Laptop Upgrade", width: 800, height: 600 },
    dellLaptopRamFanBatteryChassisOpen: { src: "/images/dell-laptop-ram-fan-battery-chassis-open.webp", alt: "Dell Laptop RAM Fan Battery Chassis Open", width: 800, height: 600 },
    desktopMotherboardHeatsinkRamSlotsHp: { src: "/images/desktop-motherboard-heatsink-ram-slots-hp.webp", alt: "Desktop Motherboard Heatsink RAM Slots HP", width: 800, height: 600 },
    disassembledHardDrivePlatterRepair: { src: "/images/disassembled-hard-drive-platter-repair.webp", alt: "Disassembled Hard Drive Platter Repair", width: 800, height: 600 },
    installingLaptopRamModuleMotherboard: { src: "/images/installing-laptop-ram-module-motherboard.webp", alt: "Installing Laptop RAM Module Motherboard", width: 800, height: 600 },
    intelOptaneM2SsdCloseup: { src: "/images/intel-optane-m2-ssd-closeup.webp", alt: "Intel Optane M.2 SSD Closeup", width: 800, height: 600 },
    kingstonDesktopRamDimmModule: { src: "/images/kingston-desktop-ram-dimm-module.webp", alt: "Kingston Desktop RAM Dimm Module", width: 800, height: 600 },
    kingstonNv21tbNvmeSsdInstallation: { src: "/images/kingston-nv2-1tb-nvme-ssd-installation.webp", alt: "Kingston Nv2 1tb NVMe SSD Installation", width: 800, height: 600 },
    laptopBottomChassisBatteryRamOpen: { src: "/images/laptop-bottom-chassis-battery-ram-open.webp", alt: "Laptop Bottom Chassis Battery RAM Open", width: 800, height: 600 },
    laptopDdr3RamSticksComparison: { src: "/images/laptop-ddr3-ram-sticks-comparison.webp", alt: "Laptop DDR3 RAM Sticks Comparison", width: 800, height: 600 },
    laptopDdr4RamModuleCloseup: { src: "/images/laptop-ddr4-ram-module-closeup.webp", alt: "Laptop DDR4 RAM Module Closeup", width: 800, height: 600 },
    laptopDualCopperHeatpipesRamSticks: { src: "/images/laptop-dual-copper-heatpipes-ram-sticks.webp", alt: "Laptop Dual Copper Heatpipes RAM Sticks", width: 800, height: 600 },
    laptopMotherboardCpuRamThermalPads: { src: "/images/laptop-motherboard-cpu-ram-thermal-pads.webp", alt: "Laptop Motherboard CPU RAM Thermal Pads", width: 800, height: 600 },
    laptopMotherboardCpuThermalPasteRamSlots: { src: "/images/laptop-motherboard-cpu-thermal-paste-ram-slots.webp", alt: "Laptop Motherboard CPU Thermal Paste RAM Slots", width: 800, height: 600 },
    laptopMotherboardCpuThermalPasteRam: { src: "/images/laptop-motherboard-cpu-thermal-paste-ram.webp", alt: "Laptop Motherboard CPU Thermal Paste RAM", width: 800, height: 600 },
    laptopMotherboardDualM2SsdSlots: { src: "/images/laptop-motherboard-dual-m2-ssd-slots.webp", alt: "Laptop Motherboard Dual M.2 SSD Slots", width: 800, height: 600 },
    laptopMotherboardFanRamSlotsRepair: { src: "/images/laptop-motherboard-fan-ram-slots-repair.webp", alt: "Laptop Motherboard Fan RAM Slots Repair", width: 800, height: 600 },
    laptopMotherboardRamHeatpipeFanRepair: { src: "/images/laptop-motherboard-ram-heatpipe-fan-repair.webp", alt: "Laptop Motherboard RAM Heatpipe Fan Repair", width: 800, height: 600 },
    laptopMotherboardRamSlotSingleStick: { src: "/images/laptop-motherboard-ram-slot-single-stick.webp", alt: "Laptop Motherboard RAM Slot Single Stick", width: 800, height: 600 },
    laptopRamSlotInstallationCloseup: { src: "/images/laptop-ram-slot-installation-closeup.webp", alt: "Laptop RAM Slot Installation Closeup", width: 800, height: 600 },
    laptopRamSticksComparisonUpgrade: { src: "/images/laptop-ram-sticks-comparison-upgrade.webp", alt: "Laptop RAM Sticks Comparison Upgrade", width: 800, height: 600 },
    laptopRamSticksMemoryUpgrade: { src: "/images/laptop-ram-sticks-memory-upgrade.webp", alt: "Laptop RAM Sticks Memory Upgrade", width: 800, height: 600 },
    laptopRamSticksStackedComparison: { src: "/images/laptop-ram-sticks-stacked-comparison.webp", alt: "Laptop RAM Sticks Stacked Comparison", width: 800, height: 600 },
    laptopSodimmRamStickHand: { src: "/images/laptop-sodimm-ram-stick-hand.webp", alt: "Laptop Sodimm RAM Stick Hand", width: 800, height: 600 },
    lenovoLaptopCoolingFanSsdSlot: { src: "/images/lenovo-laptop-cooling-fan-ssd-slot.webp", alt: "Lenovo Laptop Cooling Fan SSD Slot", width: 800, height: 600 },
    lenovoLaptopFanM2SsdSlot: { src: "/images/lenovo-laptop-fan-m2-ssd-slot.webp", alt: "Lenovo Laptop Fan M.2 SSD Slot", width: 800, height: 600 },
    m2SataSsd128gbCloseup: { src: "/images/m2-sata-ssd-128gb-closeup.webp", alt: "M.2 SATA SSD 128gb Closeup", width: 800, height: 600 },
    samsungRamModuleLaptopInstallation: { src: "/images/samsung-ram-module-laptop-installation.webp", alt: "Samsung RAM Module Laptop Installation", width: 800, height: 600 },
    seagateHardDriveDesktopPcUpgrade: { src: "/images/seagate-hard-drive-desktop-pc-upgrade.webp", alt: "Seagate Hard Drive Desktop PC Upgrade", width: 800, height: 600 },
    skHynixM2NvmeSsdInstallation: { src: "/images/sk-hynix-m2-nvme-ssd-installation.webp", alt: "Sk Hynix M.2 NVMe SSD Installation", width: 800, height: 600 },
    toshibaLaptopHardDriveHdd: { src: "/images/toshiba-laptop-hard-drive-hdd.webp", alt: "Toshiba Laptop Hard Drive HDD", width: 800, height: 600 },
    transcend2tbSsdPackaging: { src: "/images/transcend-2tb-ssd-packaging.webp", alt: "Transcend 2tb SSD Packaging", width: 800, height: 600 },
  },

  // --- MOTHERBOARD & THERMAL PASTE ---
  motherboard: {
    cpuI9: { src: "/images/intel-core-i9-13900k-cpu-asus-rog-motherboard.webp", alt: "Intel Core i9 on ASUS ROG Motherboard", width: 800, height: 600 },
    cpuRyzen: { src: "/images/amd-ryzen-7-cpu-motherboard-installation.webp", alt: "AMD Ryzen 7 CPU Installation", width: 800, height: 600 },
    gigabyteAorus: { src: "/images/gigabyte-aorus-motherboard-cpu-thermal-paste-inspection.webp", alt: "Gigabyte Aorus Thermal Paste Inspection", width: 800, height: 600 },
    breadboarding: { src: "/images/breadboarding-motherboard-with-corsair-power-supply.webp", alt: "Breadboarding Motherboard", width: 800, height: 600 },
    thermalGrizzly1: { src: "/images/applying-thermal-grizzly-kryonaut-extreme-paste.webp", alt: "Applying Thermal Grizzly Kryonaut", width: 800, height: 600 },
    thermalGrizzly2: { src: "/images/thermal-grizzly-kryonaut-extreme-packaging.webp", alt: "Thermal Grizzly Kryonaut Packaging", width: 800, height: 600 },
    thermalGrizzly3: { src: "/images/thermal-grizzly-kryonaut-extreme-syringe.webp", alt: "Thermal Grizzly Kryonaut Syringe", width: 800, height: 600 },
    thermalArctic: { src: "/images/arctic-mx6-thermal-paste-application-laptop-motherboard.webp", alt: "Arctic MX-6 Thermal Paste Application", width: 800, height: 600 },
    thermalCorsair: { src: "/images/corsair-tm30-performance-thermal-paste.webp", alt: "Corsair TM30 Thermal Paste", width: 800, height: 600 },
    thermalM12: { src: "/images/m12-high-performance-thermal-paste-jar.webp", alt: "M12 High Performance Thermal Paste", width: 800, height: 600 },
    allInOneDesktopInternalsMotherboard: { src: "/images/all-in-one-desktop-internals-motherboard.webp", alt: "All In One Desktop Internals Motherboard", width: 800, height: 600 },
    amdRyzenCpuSocketThermalPasteApplied: { src: "/images/amd-ryzen-cpu-socket-thermal-paste-applied.webp", alt: "Amd Ryzen CPU Socket Thermal Paste Applied", width: 800, height: 600 },
    applyingArcticThermalPasteCpu: { src: "/images/applying-arctic-thermal-paste-cpu.webp", alt: "Applying Arctic Thermal Paste CPU", width: 800, height: 600 },
    applyingThermalPastePcCpuBuild: { src: "/images/applying-thermal-paste-pc-cpu-build.webp", alt: "Applying Thermal Paste PC CPU Build", width: 800, height: 600 },
    cpuCoolerHeatsinkRoundCopperAluminum: { src: "/images/cpu-cooler-heatsink-round-copper-aluminum.webp", alt: "CPU Cooler Heatsink Round Copper Aluminum", width: 800, height: 600 },
    motherboardCpuSocketThermalPads: { src: "/images/motherboard-cpu-socket-thermal-pads.webp", alt: "Motherboard CPU Socket Thermal Pads", width: 800, height: 600 },
    motherboardCpuThermalPasteApplication: { src: "/images/motherboard-cpu-thermal-paste-application.webp", alt: "Motherboard CPU Thermal Paste Application", width: 800, height: 600 },
    motherboardCpuThermalPastePinkPads: { src: "/images/motherboard-cpu-thermal-paste-pink-pads.webp", alt: "Motherboard CPU Thermal Paste Pink Pads", width: 800, height: 600 },
    pcCpuCoolerBracketInstallation: { src: "/images/pc-cpu-cooler-bracket-installation.webp", alt: "PC CPU Cooler Bracket Installation", width: 800, height: 600 },
    pcMotherboardCpuSocketEmptyCloseup: { src: "/images/pc-motherboard-cpu-socket-empty-closeup.webp", alt: "PC Motherboard CPU Socket Empty Closeup", width: 800, height: 600 },
  },

  // --- HARDWARE MAINTENANCE ---
  laptopHardware: {
    brokenHinge: { src: "/images/broken-laptop-hinge-plastic-chassis-damage.webp", alt: "Broken laptop hinge chassis damage", width: 800, height: 600 },
    screenBezel: { src: "/images/laptop-screen-bezel-and-hinge-fabrication.webp", alt: "Laptop screen bezel and hinge", width: 800, height: 600 },
    cloggedFan: { src: "/images/dusty-laptop-cooling-fans-replacement.webp", alt: "Dusty laptop cooling fan replacement", width: 800, height: 600 },
    fanReplace1: { src: "/images/laptop-cooling-fan-replacements.webp", alt: "Laptop cooling fan replacement", width: 800, height: 600 },
    fanReplace2: { src: "/images/new-laptop-cooling-fan-assembly-replacement.webp", alt: "New laptop cooling fan assembly", width: 800, height: 600 },
    dualFanInspect: { src: "/images/dual-laptop-cooling-fan-assembly-inspection.webp", alt: "Dual laptop cooling fan inspection", width: 800, height: 600 },
    copperHeatsink1: { src: "/images/laptop-copper-heatsink-removal-motherboard.webp", alt: "Copper heatsink removal", width: 800, height: 600 },
    copperHeatsink2: { src: "/images/laptop-copper-heatsink-thermal-repair.webp", alt: "Copper heatsink thermal repair", width: 800, height: 600 },
    copperHeatsink3: { src: "/images/laptop-copper-heatsink-with-dried-thermal-paste.webp", alt: "Copper heatsink dried thermal paste", width: 800, height: 600 },
    dustyMotherboard: { src: "/images/laptop-motherboard-dusty-fan-and-wifi-card.webp", alt: "Dusty motherboard fan and wifi card", width: 800, height: 600 },
    laptopSpareParts: { src: "/images/laptop-spare-parts-screen-battery-keyboard-fans.webp", alt: "Laptop spare parts", width: 800, height: 600 },
    chargerInventory: { src: "/images/laptop-charger-power-adapter-inventory.webp", alt: "Laptop charger inventory", width: 800, height: 600 },
    asusAdapter: { src: "/images/asus-laptop-power-adapter-charger-repair-kuwait.webp", alt: "ASUS laptop power adapter repair", width: 800, height: 600 },
    dellAdapter: { src: "/images/dell-90w-ac-adapter-laptop-charger.webp", alt: "Dell 90W AC adapter", width: 800, height: 600 },
    dellTeardown: { src: "/images/dell-laptop-internal-hardware-teardown.webp", alt: "Dell laptop internal teardown", width: 800, height: 600 },
    dellRepair: { src: "/images/dell-laptop-open-chassis-hardware-repair.webp", alt: "Dell laptop chassis hardware repair", width: 800, height: 600 },
    dellChassis: { src: "/images/dell-latitude-laptop-bottom-chassis-inspection.webp", alt: "Dell Latitude chassis inspection", width: 800, height: 600 },
    getacBattery: { src: "/images/getac-laptop-rechargeable-battery-replacement.webp", alt: "Getac laptop battery replacement", width: 800, height: 600 },
    hpAio: { src: "/images/hp-all-in-one-desktop-pc-hardware-repair.webp", alt: "HP All-in-One PC hardware repair", width: 800, height: 600 },
    hpBattery1: { src: "/images/hp-ht03xl-laptop-battery-replacement.webp", alt: "HP HT03XL battery replacement", width: 800, height: 600 },
    hpBattery2: { src: "/images/hp-laptop-battery-replacement-service.webp", alt: "HP laptop battery service", width: 800, height: 600 },
    hpBattery3: { src: "/images/hp-notebook-battery-replacement.webp", alt: "HP notebook battery replacement", width: 800, height: 600 },
    hpAdapter1: { src: "/images/hp-laptop-ac-power-adapter-replacement.webp", alt: "HP AC power adapter replacement", width: 800, height: 600 },
    hpAdapter2: { src: "/images/hp-laptop-power-adapter-charger-replacement.webp", alt: "HP power adapter charger replacement", width: 800, height: 600 },
    hpTeardown: { src: "/images/hp-laptop-internal-hardware-diagnostics-teardown.webp", alt: "HP internal hardware diagnostics", width: 800, height: 600 },
    hpProbook: { src: "/images/hp-probook-windows-11-laptop-repair.webp", alt: "HP ProBook Windows 11 repair", width: 800, height: 600 },
    lenovoAio: { src: "/images/lenovo-ideacentre-all-in-one-desktop-repair.webp", alt: "Lenovo IdeaCentre AIO repair", width: 800, height: 600 },
    toshibaDiagnostics: { src: "/images/toshiba-laptop-windows-os-software-diagnostics.webp", alt: "Toshiba laptop OS diagnostics", width: 800, height: 600 },
    razerBsod: { src: "/images/razer-laptop-blue-screen-of-death-bsod-error-kuwait.webp", alt: "Razer laptop BSOD repair", width: 800, height: 600 },
    projectorRepair: { src: "/images/projector-and-laptop-hardware-repair-storage-kuwait.webp", alt: "Projector and laptop repair", width: 800, height: 600 },
    miniPcDiagnostics: { src: "/images/mini-pc-internal-hardware-diagnostics-and-upgrade.webp", alt: "Mini PC hardware diagnostics", width: 800, height: 600 },
    gefenMatrix: { src: "/images/gefen-toolbox-4k-ultra-hd-hdmi-matrix.webp", alt: "Gefen Toolbox 4K HDMI Matrix", width: 800, height: 600 },
    cat6Cable: { src: "/images/blue-cat6-ethernet-network-cable-installation.webp", alt: "CAT6 ethernet cable installation", width: 800, height: 600 },
    wifiIntel1: { src: "/images/intel-8265ngw-dual-band-wireless-wifi-card.webp", alt: "Intel 8265NGW Wi-Fi card", width: 800, height: 600 },
    wifiIntel2: { src: "/images/intel-dual-band-wireless-card-installation.webp", alt: "Intel dual-band wireless card install", width: 800, height: 600 },
    wifiIntel3: { src: "/images/intel-wifi-card-laptop-motherboard-repair-kuwait.webp", alt: "Intel Wi-Fi card motherboard repair", width: 800, height: 600 },
    wifiLaptop1: { src: "/images/laptop-wifi-network-card.webp", alt: "Laptop Wi-Fi network card", width: 800, height: 600 },
    wifiLaptop2: { src: "/images/laptop-wireless-network-card-replacement.webp", alt: "Laptop wireless card replacement", width: 800, height: 600 },
    intelHeatsink: { src: "/images/intel-stock-cpu-cooler-heatsink-replacement.webp", alt: "Intel stock CPU cooler replacement", width: 800, height: 600 },
    acerLaptopChargerLiteonAdapter: { src: "/images/acer-laptop-charger-liteon-adapter.webp", alt: "Acer Laptop Charger Liteon Adapter", width: 800, height: 600 },
    acerLaptopWindowsSignInScreen: { src: "/images/acer-laptop-windows-sign-in-screen.webp", alt: "Acer Laptop Windows Sign In Screen", width: 800, height: 600 },
    allInOnePcInternalsHeatpipePorts: { src: "/images/all-in-one-pc-internals-heatpipe-ports.webp", alt: "All In One PC Internals Heatpipe Ports", width: 800, height: 600 },
    applyingThermalPadLaptopMotherboard: { src: "/images/applying-thermal-pad-laptop-motherboard.webp", alt: "Applying Thermal Pad Laptop Motherboard", width: 800, height: 600 },
    applyingThermalPasteLaptopCpuBattery: { src: "/images/applying-thermal-paste-laptop-cpu-battery.webp", alt: "Applying Thermal Paste Laptop CPU Battery", width: 800, height: 600 },
    assortedLaptopChargersBoxCollection: { src: "/images/assorted-laptop-chargers-box-collection.webp", alt: "Assorted Laptop Chargers Box Collection", width: 800, height: 600 },
    assortedLaptopPowerAdaptersCollection: { src: "/images/assorted-laptop-power-adapters-collection.webp", alt: "Assorted Laptop Power Adapters Collection", width: 800, height: 600 },
    asusLaptopBatteryHeatpipeFanOpen: { src: "/images/asus-laptop-battery-heatpipe-fan-open.webp", alt: "ASUS Laptop Battery Heatpipe Fan Open", width: 800, height: 600 },
    asusLaptopDualHeatpipeFansOpen: { src: "/images/asus-laptop-dual-heatpipe-fans-open.webp", alt: "ASUS Laptop Dual Heatpipe Fans Open", width: 800, height: 600 },
    asusLaptopOpenBatteryMotherboardFan: { src: "/images/asus-laptop-open-battery-motherboard-fan.webp", alt: "ASUS Laptop Open Battery Motherboard Fan", width: 800, height: 600 },
    asusLaptopPowerAdapterCharger2: { src: "/images/asus-laptop-power-adapter-charger-2.webp", alt: "ASUS Laptop Power Adapter Charger 2", width: 800, height: 600 },
    cmosCoinCellBatteryReplacement: { src: "/images/cmos-coin-cell-battery-replacement.webp", alt: "Cmos Coin Cell Battery Replacement", width: 800, height: 600 },
    copperHeatpipeHeatsinkAssemblyRemoved: { src: "/images/copper-heatpipe-heatsink-assembly-removed.webp", alt: "Copper Heatpipe Heatsink Assembly Removed", width: 800, height: 600 },
    copperHeatsinkThermalPadsLaptop: { src: "/images/copper-heatsink-thermal-pads-laptop.webp", alt: "Copper Heatsink Thermal Pads Laptop", width: 800, height: 600 },
    ctroniqLaptopBootScreen: { src: "/images/ctroniq-laptop-boot-screen.webp", alt: "Ctroniq Laptop Boot Screen", width: 800, height: 600 },
    dell65wLaptopChargerAdapter: { src: "/images/dell-65w-laptop-charger-adapter.webp", alt: "Dell 65w Laptop Charger Adapter", width: 800, height: 600 },
    dellLaptopBsodErrorScreenRepair: { src: "/images/dell-laptop-bsod-error-screen-repair.webp", alt: "Dell Laptop BSOD Error Screen Repair", width: 800, height: 600 },
    dellLaptopCorruptedScreenGpuFailure: { src: "/images/dell-laptop-corrupted-screen-gpu-failure.webp", alt: "Dell Laptop Corrupted Screen GPU Failure", width: 800, height: 600 },
    dellLaptopWindowsUpdateRepairStack: { src: "/images/dell-laptop-windows-update-repair-stack.webp", alt: "Dell Laptop Windows Update Repair Stack", width: 800, height: 600 },
    dellVostroLaptopRepairDesk: { src: "/images/dell-vostro-laptop-repair-desk.webp", alt: "Dell Vostro Laptop Repair Desk", width: 800, height: 600 },
    deltaLaptopPowerAdapterCharger: { src: "/images/delta-laptop-power-adapter-charger.webp", alt: "Delta Laptop Power Adapter Charger", width: 800, height: 600 },
    desktopPcTowerRepairKuwait: { src: "/images/desktop-pc-tower-repair-kuwait.webp", alt: "Desktop PC Tower Repair Kuwait", width: 800, height: 600 },
    fujitsuLaptopWindowsErrorScreenRepair: { src: "/images/fujitsu-laptop-windows-error-screen-repair.webp", alt: "Fujitsu Laptop Windows Error Screen Repair", width: 800, height: 600 },
    hpDesktopTowerPcRepair: { src: "/images/hp-desktop-tower-pc-repair.webp", alt: "HP Desktop Tower PC Repair", width: 800, height: 600 },
    hpLaptopBatteryPackReplacement: { src: "/images/hp-laptop-battery-pack-replacement.webp", alt: "HP Laptop Battery Pack Replacement", width: 800, height: 600 },
    hpLaptopCopperHeatsinkDriedThermalPaste: { src: "/images/hp-laptop-copper-heatsink-dried-thermal-paste.webp", alt: "HP Laptop Copper Heatsink Dried Thermal Paste", width: 800, height: 600 },
    hpLaptopCpuCopperHeatsinkThermalPaste: { src: "/images/hp-laptop-cpu-copper-heatsink-thermal-paste.webp", alt: "HP Laptop CPU Copper Heatsink Thermal Paste", width: 800, height: 600 },
    hpLaptopDualFanHeatpipeOldThermalPaste: { src: "/images/hp-laptop-dual-fan-heatpipe-old-thermal-paste.webp", alt: "HP Laptop Dual Fan Heatpipe Old Thermal Paste", width: 800, height: 600 },
    hpLaptopMotherboardBatteryFanRepair: { src: "/images/hp-laptop-motherboard-battery-fan-repair.webp", alt: "HP Laptop Motherboard Battery Fan Repair", width: 800, height: 600 },
    hpLaptopMotherboardThermalPasteCleanup: { src: "/images/hp-laptop-motherboard-thermal-paste-cleanup.webp", alt: "HP Laptop Motherboard Thermal Paste Cleanup", width: 800, height: 600 },
    hpLaptopPowerAdapterCharger2: { src: "/images/hp-laptop-power-adapter-charger-2.webp", alt: "HP Laptop Power Adapter Charger 2", width: 800, height: 600 },
    hpPavilionLaptopOpenDesktopScreen: { src: "/images/hp-pavilion-laptop-open-desktop-screen.webp", alt: "HP Pavilion Laptop Open Desktop Screen", width: 800, height: 600 },
    hpPrinterScannerUnboxingRepair: { src: "/images/hp-printer-scanner-unboxing-repair.webp", alt: "HP Printer Scanner Unboxing Repair", width: 800, height: 600 },
    laptopBackCoverRemovedInternalsRepair: { src: "/images/laptop-back-cover-removed-internals-repair.webp", alt: "Laptop Back Cover Removed Internals Repair", width: 800, height: 600 },
    laptopBatteryMotherboardOpenRepair: { src: "/images/laptop-battery-motherboard-open-repair.webp", alt: "Laptop Battery Motherboard Open Repair", width: 800, height: 600 },
    laptopBiosDiagnosticScreenRepair: { src: "/images/laptop-bios-diagnostic-screen-repair.webp", alt: "Laptop BIOS Diagnostic Screen Repair", width: 800, height: 600 },
    laptopChargerAndWifiDeviceRepair: { src: "/images/laptop-charger-and-wifi-device-repair.webp", alt: "Laptop Charger And Wi-Fi Device Repair", width: 800, height: 600 },
    laptopChassisInteriorFanMountCables: { src: "/images/laptop-chassis-interior-fan-mount-cables.webp", alt: "Laptop Chassis Interior Fan Mount Cables", width: 800, height: 600 },
    laptopCoolingFanCleanCloseup: { src: "/images/laptop-cooling-fan-clean-closeup.webp", alt: "Laptop Cooling Fan Clean Closeup", width: 800, height: 600 },
    laptopCoolingFanCloseupRepair: { src: "/images/laptop-cooling-fan-closeup-repair.webp", alt: "Laptop Cooling Fan Closeup Repair", width: 800, height: 600 },
    laptopCoolingFanCopperHeatpipes: { src: "/images/laptop-cooling-fan-copper-heatpipes.webp", alt: "Laptop Cooling Fan Copper Heatpipes", width: 800, height: 600 },
    laptopCoolingFanReplacementPartNew: { src: "/images/laptop-cooling-fan-replacement-part-new.webp", alt: "Laptop Cooling Fan Replacement Part New", width: 800, height: 600 },
    laptopCoolingFanSilverBladesCloseup: { src: "/images/laptop-cooling-fan-silver-blades-closeup.webp", alt: "Laptop Cooling Fan Silver Blades Closeup", width: 800, height: 600 },
    laptopCopperHeatsinkHeatpipeRemoval: { src: "/images/laptop-copper-heatsink-heatpipe-removal.webp", alt: "Laptop Copper Heatsink Heatpipe Removal", width: 800, height: 600 },
    laptopCopperHeatsinkOldThermalPasteRemoval: { src: "/images/laptop-copper-heatsink-old-thermal-paste-removal.webp", alt: "Laptop Copper Heatsink Old Thermal Paste Removal", width: 800, height: 600 },
    laptopCpuThermalPasteAppliedMotherboard: { src: "/images/laptop-cpu-thermal-paste-applied-motherboard.webp", alt: "Laptop CPU Thermal Paste Applied Motherboard", width: 800, height: 600 },
    laptopCpuThermalPasteReapplication: { src: "/images/laptop-cpu-thermal-paste-reapplication.webp", alt: "Laptop CPU Thermal Paste Reapplication", width: 800, height: 600 },
    laptopDualBatteryCellsOpenChassis: { src: "/images/laptop-dual-battery-cells-open-chassis.webp", alt: "Laptop Dual Battery Cells Open Chassis", width: 800, height: 600 },
    laptopDualFanHeatpipeKeyboardBackplate: { src: "/images/laptop-dual-fan-heatpipe-keyboard-backplate.webp", alt: "Laptop Dual Fan Heatpipe Keyboard Backplate", width: 800, height: 600 },
    laptopDualHeatpipeBatteryOpenChassis: { src: "/images/laptop-dual-heatpipe-battery-open-chassis.webp", alt: "Laptop Dual Heatpipe Battery Open Chassis", width: 800, height: 600 },
    laptopDustCleaningOverheatingKuwait: { src: "/images/laptop-dust-cleaning-overheating-kuwait.webp", alt: "Laptop Dust Cleaning Overheating Kuwait", width: 800, height: 600 },
    laptopDustyFanMotherboardCloseup: { src: "/images/laptop-dusty-fan-motherboard-closeup.webp", alt: "Laptop Dusty Fan Motherboard Closeup", width: 800, height: 600 },
    laptopDustyFanWiresCloseup: { src: "/images/laptop-dusty-fan-wires-closeup.webp", alt: "Laptop Dusty Fan Wires Closeup", width: 800, height: 600 },
    laptopFanBladesCleanCloseup: { src: "/images/laptop-fan-blades-clean-closeup.webp", alt: "Laptop Fan Blades Clean Closeup", width: 800, height: 600 },
    laptopFanCopperHeatpipeCloseup: { src: "/images/laptop-fan-copper-heatpipe-closeup.webp", alt: "Laptop Fan Copper Heatpipe Closeup", width: 800, height: 600 },
    laptopFanDriedThermalPasteResidue: { src: "/images/laptop-fan-dried-thermal-paste-residue.webp", alt: "Laptop Fan Dried Thermal Paste Residue", width: 800, height: 600 },
    laptopFanDustBuildupCloseup: { src: "/images/laptop-fan-dust-buildup-closeup.webp", alt: "Laptop Fan Dust Buildup Closeup", width: 800, height: 600 },
    laptopFanDustHingeAreaCloseup: { src: "/images/laptop-fan-dust-hinge-area-closeup.webp", alt: "Laptop Fan Dust Hinge Area Closeup", width: 800, height: 600 },
    laptopHeatsinkAssemblyThermalPads: { src: "/images/laptop-heatsink-assembly-thermal-pads.webp", alt: "Laptop Heatsink Assembly Thermal Pads", width: 800, height: 600 },
    laptopHeatsinkDustGrimeBuildup: { src: "/images/laptop-heatsink-dust-grime-buildup.webp", alt: "Laptop Heatsink Dust Grime Buildup", width: 800, height: 600 },
    laptopHeatsinkShieldComponentCloseup: { src: "/images/laptop-heatsink-shield-component-closeup.webp", alt: "Laptop Heatsink Shield Component Closeup", width: 800, height: 600 },
    laptopIntelCoreI58thGenSticker: { src: "/images/laptop-intel-core-i5-8th-gen-sticker.webp", alt: "Laptop Intel Core I5 8th Gen Sticker", width: 800, height: 600 },
    laptopKeyboardHeatsinkAssemblyRemoval: { src: "/images/laptop-keyboard-heatsink-assembly-removal.webp", alt: "Laptop Keyboard Heatsink Assembly Removal", width: 800, height: 600 },
    laptopKeyboardTopCaseAssemblyRemoval: { src: "/images/laptop-keyboard-top-case-assembly-removal.webp", alt: "Laptop Keyboard Top Case Assembly Removal", width: 800, height: 600 },
    laptopLcdPanelReplacementPart: { src: "/images/laptop-lcd-panel-replacement-part.webp", alt: "Laptop LCD Panel Replacement Part", width: 800, height: 600 },
    laptopLidBackCoverPanelReplacement: { src: "/images/laptop-lid-back-cover-panel-replacement.webp", alt: "Laptop Lid Back Cover Panel Replacement", width: 800, height: 600 },
    laptopMicrosoftOfficeArabicActivationScreen: { src: "/images/laptop-microsoft-office-arabic-activation-screen.webp", alt: "Laptop Microsoft Office Arabic Activation Screen", width: 800, height: 600 },
    laptopMotherboardBluePcbHeatsinkOutline: { src: "/images/laptop-motherboard-blue-pcb-heatsink-outline.webp", alt: "Laptop Motherboard Blue Pcb Heatsink Outline", width: 800, height: 600 },
    laptopMotherboardCpuSocketChipsCloseup: { src: "/images/laptop-motherboard-cpu-socket-chips-closeup.webp", alt: "Laptop Motherboard CPU Socket Chips Closeup", width: 800, height: 600 },
    laptopMotherboardDiagnosticBenchRepair: { src: "/images/laptop-motherboard-diagnostic-bench-repair.webp", alt: "Laptop Motherboard Diagnostic Bench Repair", width: 800, height: 600 },
    laptopMotherboardDualFanHeatpipeTeardown: { src: "/images/laptop-motherboard-dual-fan-heatpipe-teardown.webp", alt: "Laptop Motherboard Dual Fan Heatpipe Teardown", width: 800, height: 600 },
    laptopMotherboardFanAgedRepair: { src: "/images/laptop-motherboard-fan-aged-repair.webp", alt: "Laptop Motherboard Fan Aged Repair", width: 800, height: 600 },
    laptopMotherboardFanHeatpipeOpen: { src: "/images/laptop-motherboard-fan-heatpipe-open.webp", alt: "Laptop Motherboard Fan Heatpipe Open", width: 800, height: 600 },
    laptopMotherboardFanHeatsinkYellowLabel: { src: "/images/laptop-motherboard-fan-heatsink-yellow-label.webp", alt: "Laptop Motherboard Fan Heatsink Yellow Label", width: 800, height: 600 },
    laptopMotherboardFanOldThermalPaste: { src: "/images/laptop-motherboard-fan-old-thermal-paste.webp", alt: "Laptop Motherboard Fan Old Thermal Paste", width: 800, height: 600 },
    laptopMotherboardGpuThermalPadsCloseup: { src: "/images/laptop-motherboard-gpu-thermal-pads-closeup.webp", alt: "Laptop Motherboard GPU Thermal Pads Closeup", width: 800, height: 600 },
    laptopMotherboardTeardownHeatsinkRemoval: { src: "/images/laptop-motherboard-teardown-heatsink-removal.webp", alt: "Laptop Motherboard Teardown Heatsink Removal", width: 800, height: 600 },
    laptopMotherboardUsbPortsCables: { src: "/images/laptop-motherboard-usb-ports-cables.webp", alt: "Laptop Motherboard USB Ports Cables", width: 800, height: 600 },
    laptopOpenRepairBench: { src: "/images/laptop-open-repair-bench.webp", alt: "Laptop Open Repair Bench", width: 800, height: 600 },
    laptopReplacementFanHeatpipeModule: { src: "/images/laptop-replacement-fan-heatpipe-module.webp", alt: "Laptop Replacement Fan Heatpipe Module", width: 800, height: 600 },
    laptopScreenAssemblyDisassemblyRepair: { src: "/images/laptop-screen-assembly-disassembly-repair.webp", alt: "Laptop Screen Assembly Disassembly Repair", width: 800, height: 600 },
    laptopScreenProtectionKuwait: { src: "/images/laptop-screen-protection-kuwait.webp", alt: "Laptop Screen Protection Kuwait", width: 800, height: 600 },
    lenovoLaptopBatteryFanHeatsinkOpen: { src: "/images/lenovo-laptop-battery-fan-heatsink-open.webp", alt: "Lenovo Laptop Battery Fan Heatsink Open", width: 800, height: 600 },
    lenovoLaptopDcPowerAdapter: { src: "/images/lenovo-laptop-dc-power-adapter.webp", alt: "Lenovo Laptop Dc Power Adapter", width: 800, height: 600 },
    lenovoLaptopPowerAdapterBrick: { src: "/images/lenovo-laptop-power-adapter-brick.webp", alt: "Lenovo Laptop Power Adapter Brick", width: 800, height: 600 },
    lenovoLaptopUsbCChargerAdapter: { src: "/images/lenovo-laptop-usb-c-charger-adapter.webp", alt: "Lenovo Laptop USB C Charger Adapter", width: 800, height: 600 },
    lenovoMax65wAcAdapterLabel: { src: "/images/lenovo-max-65w-ac-adapter-label.webp", alt: "Lenovo Max 65w AC Adapter Label", width: 800, height: 600 },
    lenovoUsbCLaptopChargerBoxed: { src: "/images/lenovo-usb-c-laptop-charger-boxed.webp", alt: "Lenovo USB C Laptop Charger Boxed", width: 800, height: 600 },
    liteonLaptopPowerAdapter: { src: "/images/liteon-laptop-power-adapter.webp", alt: "Liteon Laptop Power Adapter", width: 800, height: 600 },
    microsoftOfficeHomeStudentSoftwareBox: { src: "/images/microsoft-office-home-student-software-box.webp", alt: "Microsoft Office Home Student Software Box", width: 800, height: 600 },
    monitorBlueScreenErrorDiagnostic: { src: "/images/monitor-blue-screen-error-diagnostic.webp", alt: "Monitor Blue Screen Error Diagnostic", width: 800, height: 600 },
    silverUltrabookLaptopRepairDesk: { src: "/images/silver-ultrabook-laptop-repair-desk.webp", alt: "Silver Ultrabook Laptop Repair Desk", width: 800, height: 600 },
    thermalGrizzlyKryonautExtremePasteBox: { src: "/images/thermal-grizzly-kryonaut-extreme-paste-box.webp", alt: "Thermal Grizzly Kryonaut Extreme Paste Box", width: 800, height: 600 },
    thermalGrizzlyKryonautExtremeSyringePackage: { src: "/images/thermal-grizzly-kryonaut-extreme-syringe-package.webp", alt: "Thermal Grizzly Kryonaut Extreme Syringe Package", width: 800, height: 600 },
    thermaltakeLiquidCoolerPcBuildPurple: { src: "/images/thermaltake-liquid-cooler-pc-build-purple.webp", alt: "Thermaltake Liquid Cooler PC Build Purple", width: 800, height: 600 },
    thinkpadLaptopInstallingWindows11: { src: "/images/thinkpad-laptop-installing-windows-11.webp", alt: "ThinkPad Laptop Installing Windows 11", width: 800, height: 600 },
    thinkpadLaptopWindowsDesktopRepair: { src: "/images/thinkpad-laptop-windows-desktop-repair.webp", alt: "ThinkPad Laptop Windows Desktop Repair", width: 800, height: 600 },
    thinkpadX1CarbonTouchCableFlex30pin: { src: "/images/thinkpad-x1-carbon-touch-cable-flex-30pin.webp", alt: "ThinkPad X1 Carbon Touch Cable Flex 30-pin", width: 800, height: 600 },
    toshibaLaptopTechnicianDiagnosticReflection: { src: "/images/toshiba-laptop-technician-diagnostic-reflection.webp", alt: "Toshiba Laptop Technician Diagnostic Reflection", width: 800, height: 600 },
    windowsMemoryDiagnosticTestScreen: { src: "/images/windows-memory-diagnostic-test-screen.webp", alt: "Windows Memory Diagnostic Test Screen", width: 800, height: 600 },
  }
} as const;
